// bachelor-front-vue-version-main/src/components/administrator_management_tool_view/BusinessPageListItem.vue
<template>
  <div class="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
    <span class="c-text-14 truncate">{{ businessPage.businessDescription.legalName }}</span>
    <div class="flex items-center gap-x-3 flex-wrap">
      <c-button-secondary @click="isBusinessProductsDialogShown = true" :text="$t('products')"></c-button-secondary>
      <c-button-secondary @click="isBusinessOverviewDialogShown = true" :text="$t('overview')"></c-button-secondary>
    </div>
    <c-dialog width="736" v-model="isBusinessOverviewDialogShown">
      <template #title>
        <h3>{{ $t("businessOverview") }}</h3>
      </template>
      <template #body>
        <business-overview :business="businessPage"></business-overview>
      </template>
      <template #footer>
        <div class="mt-3 flex items-center justify-end">
          <c-button-secondary @click="isBusinessOverviewDialogShown = false" :text="$t('close')"></c-button-secondary>
        </div>
      </template>
    </c-dialog>
    <c-dialog width="736" v-model="isBusinessProductsDialogShown">
      <template #title>
        <h3 class="mb-8">{{ businessPage.businessDescription.legalName + " " + $t("products").toLowerCase() }}</h3>
      </template>
      <template #body>
        <div
          class="flex flex-col grow items-center justify-center"
          v-if="!products.length">
          <h4 class="text-spun-pearl">{{ $t("empty") }}</h4>
        </div>
        <div v-else class="flex flex-col">
          <div class="flex flex-col gap-y-3">
            <business-page-list-item-product-list-item
              @productDeleted="fetchProductsLocal(1)"
              v-for="product in products"
              :key="product.id"
              :product="product">
            </business-page-list-item-product-list-item>
          </div>
          <c-pagination
            v-if="productsTotalPages > 1"
            @currentPageChanged="handlePageChange"
            class="mt-8 self-center"
            :total-pages="productsTotalPages"
            :current-page="productsCurrentPage"
          ></c-pagination>
        </div>
      </template>
      <template #footer>
        <div class="mt-8 flex items-center justify-end">
          <c-button-secondary @click="isBusinessProductsDialogShown = false" :text="$t('close')"></c-button-secondary>
        </div>
      </template>
    </c-dialog>
  </div>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary";
import CDialog from "@/components/common/CDialog";
import BusinessOverview from "@/components/administrator_management_tool_view/BusinessOverview";
import CPagination from "@/components/common/CPagination";
import BusinessPageListItemProductListItem
  from "@/components/administrator_management_tool_view/BusinessPageListItemProductListItem";

export default {
  name: "BusinessPageListItem",
  components: {
    BusinessPageListItemProductListItem,
    CButtonSecondary,
    CDialog,
    BusinessOverview,
    CPagination
  },
  props: {
    businessPage: {
      type: Object,
      required: true
    }
  },
  watch: {
    isBusinessProductsDialogShown: {
      handler(newValue) {
        if (newValue) {
          if (!this.products.length) {
            this.fetchProductsLocal(1);
          }
        }
      }
    }
  },
  data() {
    return {
      isBusinessProductsDialogShown: false,
      isBusinessOverviewDialogShown: false,

      products: [],
      productsCurrentPage: 1,
      productsTotalPages: 1
    };
  },
  methods: {
    handlePageChange(page) {
      this.fetchProductsLocal(page);
    },
    fetchProductsLocal(page) {
      this.$store.dispatch("administratorManagementToolModule/fetchProducts", {
        page: page,
        businessId: this.businessPage.id
      }).then((response) => {
        this.products = response.productList;
        this.productsCurrentPage = page;
        this.productsTotalPages = response.totalAmountOfPages;
      }).catch(() => this.$store.dispatch("eventModule/showSnackbar", {
        message: this.$t("somethingWentWrong"),
        type: "error"
      }));
    }
  }
};
</script>

<style scoped>

</style>

// bachelor-front-react-version-main/src/components/administrator-management-tool/BusinessPageListItem.tsx
import { Business } from "../../generated-sources/openapi";
import { useTranslation } from "react-i18next";
import { useDispatch } from "react-redux";
import { useEffect, useState } from "react";
import { fetchProducts } from "../../store/administratorManagementToolSlice";
import { showSnackbar } from "../../store/eventSlice";
import CButtonSecondary from "../common/CButtonSecondary";
import CDialog from "../common/CDialog";
import BusinessOverview from "./BusinessOverview";
import BusinessPageListItemProductListItem from "./BusinessPageListItemProductListItem";
import CPagination from "../common/CPagination";

interface Props {
  businessPage: Business;
}

function BusinessPageListItem(props: Props) {
  const { t } = useTranslation();
  const dispatch = useDispatch();

  const { businessPage } = props;

  const [isBusinessProductsDialogShown, setIsBusinessProductsDialogShown] = useState(false);
  const [isBusinessOverviewDialogShown, setIsBusinessOverviewDialogShown] = useState(false);
  const [products, setProducts] = useState([]);
  const [productsCurrentPage, setProductsCurrentPage] = useState(1);
  const [productsTotalPages, setProductsTotalPages] = useState(1);

  useEffect(() => {
    if (isBusinessProductsDialogShown) {
      if (!products.length) {
        fetchProductsLocal(1);
      }
    }
  }, [isBusinessProductsDialogShown]);

  function handlePageChange(page: number) {
    fetchProductsLocal(page);
  }

  function handleProductDeleted() {
    fetchProductsLocal(1);
  }

  function fetchProductsLocal(page: number) {
    // @ts-ignore
    dispatch(fetchProducts(page, businessPage.id))
      .then((response: any) => {
        setProducts(response.productList);
        setProductsCurrentPage(page);
        setProductsTotalPages(response.totalAmountOfPages);
      })
      .catch(() =>
        dispatch(
          showSnackbar({
            message: t("somethingWentWrong"),
            type: "error",
          })
        )
      );
  }

  return (
    <div className="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
      <span className="c-text-14 truncate">{businessPage.businessDescription.legalName}</span>
      <div className="flex items-center gap-x-3 flex-wrap">
        <CButtonSecondary
          text={t("products")}
          onClick={() => setIsBusinessProductsDialogShown(true)}></CButtonSecondary>
        <CButtonSecondary
          text={t("overview")}
          onClick={() => setIsBusinessOverviewDialogShown(true)}></CButtonSecondary>
      </div>
      <CDialog
        isShown={isBusinessOverviewDialogShown}
        onUpdate={setIsBusinessOverviewDialogShown}
        width={"md"}
        titleSlot={<h3>{t("businessOverview")}</h3>}
        footerSlot={
          <div className="mt-3 flex items-center justify-end">
            <CButtonSecondary
              text={t("close")}
              onClick={() => setIsBusinessOverviewDialogShown(false)}></CButtonSecondary>
          </div>
        }>
        <BusinessOverview business={businessPage}></BusinessOverview>
      </CDialog>
      <CDialog
        titleSlot={
          <h3 className="mb-8">{businessPage.businessDescription.legalName + " " + t("products").toLowerCase()}</h3>
        }
        footerSlot={
          <div className="mt-8 flex items-center justify-end">
            <CButtonSecondary
              text={t("close")}
              onClick={() => setIsBusinessProductsDialogShown(false)}></CButtonSecondary>
          </div>
        }
        isShown={isBusinessProductsDialogShown}
        onUpdate={setIsBusinessProductsDialogShown}
        width={"md"}>
        {!products.length ? (
          <div className={"flex flex-col grow items-center justify-center"}>
            <h4 className="text-spun-pearl">{t("empty")}</h4>
          </div>
        ) : (
          <div className={"flex flex-col"}>
            <div className={"flex flex-col gap-y-3"}>
              {products.map((product: any) => (
                <BusinessPageListItemProductListItem
                  key={product.id}
                  onProductDeleted={handleProductDeleted}
                  product={product}></BusinessPageListItemProductListItem>
              ))}
            </div>
            {productsTotalPages > 1 && (
              <CPagination
                className={"mt-8 self-center"}
                onCurrentPageChanged={handlePageChange}
                currentPage={productsCurrentPage}
                totalPages={productsTotalPages}></CPagination>
            )}
          </div>
        )}
      </CDialog>
    </div>
  );
}

export default BusinessPageListItem;
