// bachelor-front-vue-version-main/src/components/administrator_management_tool_view/SupportDiscussionListItem.vue
<template>
  <div class="min-h-14 border border-solid border-mid-gray flex flex-row items-center px-5 py-[17px] justify-between">
    <div class="flex flex-col gap-1">
      <div class="flex flex-row items-center gap-x-3">
        <font-awesome-icon size="xs" icon="fa-solid fa-calendar-days"></font-awesome-icon>
        <span class="c-text-14 truncate">{{ getFormattedDateTime(discussion.createdDate) }}</span>
      </div>
      <div class="flex flex-row items-center gap-x-3">
        <font-awesome-icon size="xs" icon="fa-solid fa-question"></font-awesome-icon>
        <span :title="discussion.threadTopic" class="c-text-14 truncate">{{ discussion.threadTopic }}</span>
      </div>
    </div>
    <c-button-secondary @click="isThreadDialogShown = true" :text="$t('seeDetails')"></c-button-secondary>
    <c-dialog v-model="isThreadDialogShown" width="644"
              content-class-overwrite="border border-mid-gray border-solid bg-white focus-visible:outline-none flex flex-col">
      <template #body>
        <c-dialog :title="$t('deleteDiscussion')"
                  @confirm="closeIssue()" :subtitle-text="$t('deleteDiscussionSubtitle')"
                  v-model="isConfirmDeleteDialogShown"></c-dialog>
        <div class="flex flex-col">
          <div class="border-solid border-b border-mid-gray flex-col sticky top-0 bg-white">
            <c-comment class="px-8 mb-3" :is-reply-enabled="false">
              <template #author>
                {{ $t("askedBy", { author: discussion.threadAuthorEmail }) }}
              </template>
              <template #date>
                {{ getFormattedDateTime(discussion.createdDate) }}
              </template>
              <template #text>
                {{ discussion.threadTopic }}
              </template>
            </c-comment>
          </div>
          <c-comment class="ml-12 px-8" v-for="(message) in messages" :key="message.threadReplyId"
                     :is-reply-enabled="false"
                     :message-object="message">
            <template #author="{author}">
              {{ author.isCreatorOfTheThread ? discussion.threadAuthorEmail : $t("you") }}
            </template>
          </c-comment>
          <div v-if="!messages.length" class="flex flex-col grow min-h-[144px] items-center justify-center mt-6">
            <h4 class="text-spun-pearl">{{ $t("noMessages") }}</h4>
          </div>
          <div id="target-last-item"></div>
          <div class="pb-4 sticky bottom-0 bg-white mt-6 pt-3 border-t border-solid border-mid-gray">
            <div class="ml-12 flex flex-col px-8">
              <c-textarea :is-disabled="isReplyLoading" grow ref="cTextareaNewMessage" size="small" v-model="newMessage"
                          :rows="2"
                          :validate-on-blur="false" :validator-functions="[validateRequired]"
                          :placeholder="$t('typeANewMessage')"></c-textarea>
              <div class="flex flex-row justify-end gap-6 mt-3 items-center flex-wrap">
                <c-button-secondary @click="handleCloseIssue()" :text="$t('closeIssue')"></c-button-secondary>
                <c-button-secondary @click="isThreadDialogShown = false" :text="$t('exitDialog')"></c-button-secondary>
                <c-button-primary :is-disabled="isReplyLoading" @click="handleSendNewMessage()"
                                  icon-end="fa-solid fa-paper-plane"
                                  class="self-end"
                                  :text="$t('send')"></c-button-primary>
              </div>
            </div>
          </div>
        </div>
      </template>
      <template #footer>
        <div></div>
      </template>
    </c-dialog>
  </div>
</template>

<script>
import dateFormatterMixin from "@/util/dateFormatterMixin";
import CButtonSecondary from "@/components/common/CButtonSecondary.vue";
import CDialog from "@/components/common/CDialog.vue";
import CComment from "@/components/common/CComment.vue";
import CTextarea from "@/components/common/CTextarea.vue";
import CButtonPrimary from "@/components/common/CButtonPrimary.vue";
import validatorMixin from "@/util/validatorMixin";

export default {
  name: "SupportDiscussionListItem",
  mixins: [dateFormatterMixin, validatorMixin],
  props: {
    discussion: {
      type: Object,
      required: true
    }
  },
  components: {
    CButtonSecondary,
    CDialog,
    CComment,
    CTextarea,
    CButtonPrimary
  },
  watch: {
    isThreadDialogShown(newValue) {
      if (newValue) {
        this.$store.dispatch("eventModule/showLoadingOverlay");
        this.fetchMessagesLocal()
          .finally(() => {
            this.$store.dispatch("eventModule/hideLoadingOverlay");
          });
        this.startFakeWebsocket();
      } else {
        this.stopFakeWebsocket();
        this.reset();
      }
    }
  },
  data() {
    return {
      isThreadDialogShown: false,
      isConfirmDeleteDialogShown: false,

      messages: [],
      isReplyLoading: false,
      newMessage: "",

      fakeWebsocket: null
    };
  },
  methods: {
    scrollToLastItem() {
      setTimeout(() => {
        document.getElementById("target-last-item")?.scrollIntoView({behavior: 'smooth'});
      }, 0);
    },
    reset() {
      this.newMessage = "";
      this.threadInfo = null;
      this.isConfirmDeleteDialogShown = false;

      this.isReplyLoading = false;
      this.messages = [];
    },
    handleCloseIssue() {
      this.isConfirmDeleteDialogShown = true;
    },
    closeIssue() {
      this.$store.dispatch("administratorManagementToolModule/closeSupportThread", { supportThreadId: this.discussion.supportThreadId })
        .then(() => {
          this.isThreadDialogShown = false;
          this.$store.dispatch(
            "administratorManagementToolModule/fetchThreads", 1
          );
        });
    },
    handleSendNewMessage() {
      let isMessageValid = this.$refs.cTextareaNewMessage.validateInput();
      if (isMessageValid) {
        this.isReplyLoading = true;
        this.$store.dispatch("administratorManagementToolModule/createThreadReply", {
          supportThreadId: this.discussion.supportThreadId,
          text: this.newMessage
        })
          .then(() => {
            this.newMessage = "";
          })
          .catch(() => {
            this.$store.dispatch("eventModule/showSnackbar", {
              message: this.$t("failedToPostMessage"),
              type: "error"
            });
          })
          .finally(() => {
            this.isReplyLoading = false;
            this.fetchMessagesLocal();
          });
      }
    },
    fetchMessagesLocal(scrollIntoView = true) {
      return this.$store.dispatch("administratorManagementToolModule/fetchMessages", this.discussion.supportThreadId)
        .then((response) => {
          this.messages = this.messages = response.data.ThreadReplyPageList;
          if (this.messages.length && scrollIntoView) {
            this.scrollToLastItem();
          }
        })
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$t("failedToFetchMessages"),
            type: "error"
          });
        });
    },
    startFakeWebsocket() {
      this.fakeWebsocket = setInterval(() => {
        this.fetchMessagesLocal(false);
      }, 10000);
    },
    stopFakeWebsocket() {
      clearInterval(this.fakeWebsocket);
    }
  }
};
</script>

<style scoped>

</style>

// bachelor-front-react-version-main/src/components/administrator-management-tool/SupportDiscussionListItem.tsx
import { SupportThread, ThreadReply } from "../../generated-sources/openapi";
import { useDispatch } from "react-redux";
import { useTranslation } from "react-i18next";
import { useEffect, useRef, useState } from "react";
import { hideLoadingOverlay, showLoadingOverlay, showSnackbar } from "../../store/eventSlice";
import {
  closeSupportThread,
  createThreadReply,
  fetchMessages,
  fetchThreads,
} from "../../store/administratorManagementToolSlice";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { dateFormatterHelper } from "../../utils/dateFormatterHelper";
import CButtonSecondary from "../common/CButtonSecondary";
import CDialog from "../common/CDialog";
import CComment from "../common/CComment";
import CTextarea from "../common/CTextarea";
import { validatorHelper } from "../../utils/validatorHelper";
import CButtonPrimary from "../common/CButtonPrimary";

interface Props {
  discussion: SupportThread;
}

function SupportDiscussionListItem(props: Props) {
  const { t } = useTranslation();
  const dispatch = useDispatch();

  const { discussion } = props;

  const [isThreadDialogShown, setIsThreadDialogShown] = useState(false);
  const [isConfirmDeleteDialogShown, setIsConfirmDeleteDialogShown] = useState(false);
  const [messages, setMessages] = useState<ThreadReply[]>([]);
  const [isReplyLoading, setIsReplyLoading] = useState(false);
  const [newMessage, setNewMessage] = useState("");
  const [fakeWebsocket, setFakeWebsocket] = useState<any>(null);

  const cTextareaNewMessageRef = useRef(null);

  useEffect(() => {
    if (isThreadDialogShown) {
      dispatch(showLoadingOverlay({ isInstant: false }));
      fetchMessagesLocal().finally(() => dispatch(hideLoadingOverlay()));
      startFakeWebsocket();
    } else {
      stopFakeWebsocket();
      reset();
    }
  }, [isThreadDialogShown]);

  function scrollToLastItem() {
    setTimeout(() => {
      document.getElementById("target-last-item")?.scrollIntoView({ behavior: "smooth" });
    }, 0);
  }

  function handleCloseIssue() {
    setIsConfirmDeleteDialogShown(true);
  }

  function closeIssue() {
    // @ts-ignore
    dispatch(closeSupportThread({ supportThreadId: discussion.supportThreadId })).then(() => {
      setIsThreadDialogShown(false);
      // @ts-ignore
      dispatch(fetchThreads(1));
    });
  }

  function reset() {
    setNewMessage("");
    setIsConfirmDeleteDialogShown(false);
    setIsReplyLoading(false);
    setMessages([]);
  }

  function handleSendNewMessage() {
    // @ts-ignore
    let isMessageValid = cTextareaNewMessageRef.current.validateInput();
    if (isMessageValid) {
      setIsReplyLoading(true);
      dispatch(
        // @ts-ignore
        createThreadReply({
          supportThreadId: discussion.supportThreadId,
          text: newMessage,
        })
      )
        .then(() => setNewMessage(""))
        .catch(() =>
          dispatch(
            showSnackbar({
              message: t("failedToPostMessage"),
              type: "error",
            })
          )
        )
        .finally(() => {
          setIsReplyLoading(false);
          fetchMessagesLocal();
        });
    }
  }

  function fetchMessagesLocal(scrollIntoView = true) {
    // @ts-ignore
    return dispatch(fetchMessages(discussion.supportThreadId))
      .then((response: any) => {
        setMessages(response.data.ThreadReplyPageList);
        if (messages.length && scrollIntoView) {
          scrollToLastItem();
        }
      })
      .catch(() => {
        dispatch(
          showSnackbar({
            message: t("failedToFetchMessages"),
            type: "error",
          })
        );
      });
  }

  function startFakeWebsocket() {
    setFakeWebsocket(
      setInterval(() => {
        fetchMessagesLocal(false);
      }, 10000)
    );
  }

  function stopFakeWebsocket() {
    clearInterval(fakeWebsocket);
  }

  return (
    <div className="min-h-14 border border-solid border-mid-gray flex flex-row items-center px-5 py-[17px] justify-between">
      <div className="flex flex-col gap-1">
        <div className="flex flex-row items-center gap-x-3">
          <FontAwesomeIcon size={"xs"} icon={["fas", "calendar-days"]}></FontAwesomeIcon>
          <span className={"c-text-14 truncate"}>
            {dateFormatterHelper.getFormattedDateTime(discussion.createdDate || "")}
          </span>
        </div>
        <div className="flex flex-row items-center gap-x-3">
          <FontAwesomeIcon size={"xs"} icon={["fas", "question"]}></FontAwesomeIcon>
          <span title={discussion.threadTopic} className="c-text-14 truncate">
            {discussion.threadTopic}
          </span>
        </div>
      </div>
      <CButtonSecondary text={t("seeDetails")} onClick={() => setIsThreadDialogShown(true)} />
      <CDialog isShown={isThreadDialogShown} onUpdate={setIsThreadDialogShown} footerSlot={<div></div>}>
        <CDialog
          isShown={isConfirmDeleteDialogShown}
          onUpdate={setIsConfirmDeleteDialogShown}
          onConfirm={closeIssue}
          subtitleText={t("deleteDiscussionSubtitle") || ""}
          titleText={t("deleteDiscussion") || ""}></CDialog>
        <div className="flex flex-col">
          <div className="border-solid border-b border-mid-gray flex-col sticky top-0 bg-white">
            <CComment
              className={"px-8 mb-3"}
              isReplyEnabled={false}
              authorSlot={() => t("askedBy", { author: discussion.threadAuthorEmail })}
              textSlot={discussion.threadTopic}
              dateSlot={dateFormatterHelper.getFormattedDateTime(discussion.createdDate || "")}></CComment>
          </div>
          {messages.map((message, index) => (
            <CComment
              className={"ml-12 px-8"}
              key={message.threadReplyId}
              isReplyEnabled={false}
              messageObject={message}
              authorSlot={(author: any) =>
                author.isCreatorOfTheThread ? discussion.threadAuthorEmail : t("you")
              }></CComment>
          ))}
          {!messages.length && (
            <div className={"flex flex-col grow min-h-[144px] items-center justify-center mt-6"}>
              <h4 className="text-spun-pearl">{t("noMessages")}</h4>
            </div>
          )}
          <div id="target-last-item"></div>
          <div className="pb-4 sticky bottom-0 bg-white mt-6 pt-3 border-t border-solid border-mid-gray">
            <div className="ml-12 flex flex-col px-8">
              <CTextarea
                isDisabled={isReplyLoading}
                grow={true}
                ref={cTextareaNewMessageRef}
                value={newMessage}
                onUpdate={setNewMessage}
                rows={2}
                validateOnBlur={false}
                validatorFunctions={[validatorHelper.validateRequired]}
                placeholder={t("typeANewMessage") || ""}
                size={"small"}></CTextarea>
              <div className="flex flex-row justify-end gap-6 mt-3 items-center flex-wrap">
                <CButtonSecondary onClick={handleCloseIssue} text={t("closeIssue")}></CButtonSecondary>
                <CButtonSecondary
                  onClick={() => setIsThreadDialogShown(false)}
                  text={t("exitDialog")}></CButtonSecondary>
                <CButtonPrimary
                  iconEnd={["fas", "paper-plane"]}
                  className={"self-end"}
                  onClick={handleSendNewMessage}
                  text={t("send")}
                  isDisabled={isReplyLoading}></CButtonPrimary>
              </div>
            </div>
          </div>
        </div>
      </CDialog>
    </div>
  );
}

export default SupportDiscussionListItem;
