// bachelor-front-react-version-main/src/components/edit-business-page/EditBusinessPageLegalBusinessInformation.tsx
import { useRef, useState } from "react";
import EditBusinessPageStepTemplate from "./EditBusinessPageStepTemplate";
import { useTranslation } from "react-i18next";
import { RootState } from "../../store";
import { useDispatch, useSelector } from "react-redux";
import {
  setBusinessApplicationBankStatementFileKey,
  setBusinessApplicationBankStatementFileUrl,
  setBusinessApplicationBusinessEntityType,
  setBusinessApplicationRegistrationCertificateFileUrl,
  setBusinessApplicationRegistrationCertificateKey,
  setBusinessApplicationTvaNumber,
  setBusinessApplicationUniqueIdentificationCode,
  uploadLegalDocuments,
} from "../../store/businessManagementToolSlice";
import CInput from "../common/CInput";
import { validatorHelper } from "../../utils/validatorHelper";
import CMenu from "../common/CMenu";
import CButtonPrimary from "../common/CButtonPrimary";
import CInfo from "../common/CInfo";
import CFileInput from "../common/CFileInput";
import { hideLoadingOverlay, showLoadingOverlay, showSnackbar } from "../../store/eventSlice";
import { BusinessDescriptionBusinessEntityTypeEnum } from "../../generated-sources/openapi";

interface Props {
  isCreate: boolean;
  isDisabled: boolean;
  isEditMode: boolean;
  stepHeaderClicked: () => void;
  nextStepClicked: () => void;
  previousStepClicked: () => void;
}

function EditBusinessPageLegalBusinessInformation(props: Props) {
  const { t } = useTranslation();
  const dispatch = useDispatch();

  const { isCreate, isDisabled, isEditMode, stepHeaderClicked, nextStepClicked, previousStepClicked } = props;

  const { uniqueIdentificationCode, tvaNumber, businessEntityType } = useSelector(
    // @ts-ignore
    (state: RootState) => state.businessManagementTool.businessApplication.businessDescription || {}
  );

  const { registrationCertificateKey, registrationCertificateFileUrl, bankStatementFileKey, bankStatementFileUrl } =
    useSelector(
      // @ts-ignore
      (state: RootState) => state.businessManagementTool.businessApplication.businessLegalDocuments || {}
    );

  const [tempRegistrationCertificateFile, setTempRegistrationCertificateFile] = useState<any>(null);
  const [tempBankStatementFile, setTempBankStatementFile] = useState<any>(null);

  const cInputIdentificationCodeRef = useRef<any>(null);
  const cInputTvaCodeRef = useRef<any>(null);
  const cFileInputRegistrationCertificateRef = useRef<any>(null);
  const cFileInputBankStatementRef = useRef<any>(null);

  let businessEntityTypeOptions = [];

  for (let key in BusinessDescriptionBusinessEntityTypeEnum) {
    businessEntityTypeOptions.push({
      // @ts-ignore
      text: BusinessDescriptionBusinessEntityTypeEnum[key],
      // @ts-ignore
      selected: businessEntityType === BusinessDescriptionBusinessEntityTypeEnum[key],
      function: () =>
        // @ts-ignore
        handleSetBusinessApplicationBusinessEntityType(BusinessDescriptionBusinessEntityTypeEnum[key]),
    });
  }

  function handleSetBusinessApplicationUniqueIdentificationCode(newValue: string) {
    dispatch(setBusinessApplicationUniqueIdentificationCode(newValue));
  }

  function handleSetBusinessApplicationTvaNumber(newValue: string) {
    dispatch(setBusinessApplicationTvaNumber(newValue));
  }

  function handleSetBusinessApplicationBusinessEntityType(newValue: string) {
    dispatch(setBusinessApplicationBusinessEntityType(newValue));
  }

  function handleNextStepClicked(e?: any) {
    if (e) e.preventDefault();

    let isIdentificationCodeValid = cInputIdentificationCodeRef.current.validateInput();
    let isTvaCodeValid = cInputTvaCodeRef.current.validateInput();
    let isLegalDocumentsValid = validateLegalDocuments();

    if (isIdentificationCodeValid && isTvaCodeValid && isLegalDocumentsValid) nextStepClicked();
  }

  function registrationCertificateSelected(registrationCertificate: File) {
    setTempRegistrationCertificateFile(registrationCertificate);
    if (tempBankStatementFile) {
      uploadLegalDocumentsLocal();
    }
  }

  function bankStatementSelected(bankStatement: File) {
    setTempBankStatementFile(bankStatement);
    if (tempRegistrationCertificateFile) {
      uploadLegalDocumentsLocal();
    }
  }

  function uploadLegalDocumentsLocal() {
    dispatch(showLoadingOverlay({ isInstant: true }));
    dispatch(
      // @ts-ignore
      uploadLegalDocuments({
        registrationCertificate: tempRegistrationCertificateFile,
        bankStatement: tempBankStatementFile,
      })
    )
      .then((response: any) => {
        dispatch(setBusinessApplicationRegistrationCertificateKey(response.data.registrationCertificateKey));
        dispatch(setBusinessApplicationRegistrationCertificateFileUrl(response.data.registrationCertificateFileUrl));
        dispatch(setBusinessApplicationBankStatementFileKey(response.data.bankStatementFileKey));
        dispatch(setBusinessApplicationBankStatementFileUrl(response.data.bankStatementFileUrl));
      })
      .catch(() => {
        dispatch(
          showSnackbar({
            message: t("somethingWentWrongWhileUploadingTheFile", { count: 2 }),
            type: "error",
          })
        );
        cFileInputRegistrationCertificateRef.current.reset();
        cFileInputBankStatementRef.current.reset();
        setTempRegistrationCertificateFile(null);
        setTempBankStatementFile(null);
        cFileInputRegistrationCertificateRef.current.validateInput();
        cFileInputBankStatementRef.current.validateInput();
      })
      .finally(() => dispatch(hideLoadingOverlay()));
  }

  function validateLegalDocuments() {
    if (registrationCertificateKey && registrationCertificateFileUrl && bankStatementFileKey && bankStatementFileUrl) {
      return true;
    } else {
      if (!tempRegistrationCertificateFile) {
        cFileInputRegistrationCertificateRef.current.reset();
        cFileInputRegistrationCertificateRef.current.validateInput();
      }
      if (!tempBankStatementFile) {
        cFileInputBankStatementRef.current.reset();
        cFileInputBankStatementRef.current.validateInput();
      }
      return false;
    }
  }

  return (
    <EditBusinessPageStepTemplate
      stepHeaderClicked={stepHeaderClicked}
      nextStepClicked={handleNextStepClicked}
      previousStepClicked={previousStepClicked}
      stepNumber={2}
      stepTitle={t("legalBusinessInformation")}
      isEditMode={isEditMode}
      isDisabled={isDisabled}>
      <form className={"flex flex-col"} onSubmit={handleNextStepClicked}>
        <CInput
          ref={cInputIdentificationCodeRef}
          value={uniqueIdentificationCode + ""}
          onUpdate={handleSetBusinessApplicationUniqueIdentificationCode}
          inputSize={"medium"}
          labelText={t("identificationCode") + " *"}
          validatorFunctions={[validatorHelper.validateRequired, validatorHelper.validateIsInteger]}></CInput>
        <CInput
          className={"mt-8"}
          ref={cInputTvaCodeRef}
          value={tvaNumber + ""}
          onUpdate={handleSetBusinessApplicationTvaNumber}
          inputSize={"medium"}
          labelText={t("tvaCode") + " *"}
          validatorFunctions={[validatorHelper.validateRequired, validatorHelper.validateIsInteger]}></CInput>
        <span className="block c-text-14 mt-8 mb-2">{t("businessEntityType") + " *"}</span>
        <div className="inline-block">
          <CMenu items={businessEntityTypeOptions} isRadio={true}>
            <CButtonPrimary type="button" iconEnd={["fas", "chevron-down"]} text={businessEntityType}></CButtonPrimary>
          </CMenu>
        </div>
        {isCreate ? (
          <CInfo className={"max-w-sm mt-10"} text={t("theFilesBelowHaveToBeInPdfFormat") || ""}></CInfo>
        ) : (
          <CInfo
            className={"max-w-sm mt-10"}
            text={
              t("theFilesBelowHaveToBeInPdfFormat") +
              "\n" +
              t("pleaseBeAwareThatIfYouNeedToReUploadOneFileYouWillHaveTo").toUpperCase()
            }></CInfo>
        )}
        <CFileInput
          ref={cFileInputRegistrationCertificateRef}
          accept="application/pdf"
          className={"mt-8"}
          labelText={t("registrationCertificate") + " *"}
          onFileSelected={registrationCertificateSelected}
          nonNativeFileName={registrationCertificateKey ? t("somePdfUploaded") || "" : ""}></CFileInput>
        <CFileInput
          ref={cFileInputBankStatementRef}
          accept="application/pdf"
          className={"mt-8"}
          labelText={t("bankStatement") + " *"}
          onFileSelected={bankStatementSelected}
          nonNativeFileName={bankStatementFileKey ? t("somePdfUploaded") || "" : ""}></CFileInput>
      </form>
    </EditBusinessPageStepTemplate>
  );
}

export default EditBusinessPageLegalBusinessInformation;

// bachelor-front-vue-version-main/src/components/edit_business_page_view/EditBusinessPageLegalBusinessInformation.vue
<template>
  <edit-business-page-step-template
    @stepHeaderClicked="$emit('stepHeaderClicked')"
    @nextStepClicked="handleNextStepClicked"
    @previousStepClicked="$emit('previousStepClicked')"
    :step-title="$t('legalBusinessInformation')"
    :step-number="2"
    :is-edit-mode="isEditMode"
    :is-disabled="isDisabled"
  >
    <c-input
      ref="cInputIdentificationCode"
      v-model="identificationCode"
      size="medium"
      :label-text="$t('identificationCode') + ' *'"
      :validator-functions="[validateRequired, validateIsInteger]"
    ></c-input>
    <c-input
      class="mt-8"
      ref="cInputTvaCode"
      v-model="tvaCode"
      size="medium"
      :label-text="$t('tvaCode') + ' *'"
      :validator-functions="[validateRequired, validateIsInteger]"
    ></c-input>
    <span class="block c-text-14 mt-8 mb-2">
      {{ $t("businessEntityType") + " *" }}
    </span>
    <div class="inline-block">
      <c-menu
        is-radio
        :items="[
          {
            name: 'SRL',
            selected: businessEntityType === 'SRL',
            function: () => (businessEntityType = 'SRL'),
          },
          {
            name: 'SNC',
            selected: businessEntityType === 'SNC',
            function: () => (businessEntityType = 'SNC'),
          },
          {
            name: 'SC',
            selected: businessEntityType === 'SC',
            function: () => (businessEntityType = 'SC'),
          },
          {
            name: 'SA',
            selected: businessEntityType === 'SA',
            function: () => (businessEntityType = 'SA'),
          },
        ]"
      >
        <template #activator>
          <c-button-primary
            type="button"
            :text="businessEntityType"
            icon-end="fa-solid fa-chevron-down"
          ></c-button-primary>
        </template>
      </c-menu>
    </div>
    <c-info
      style="max-width: calc(96px * 4)"
      v-if="isCreate"
      class="mt-10"
      :text="$t('theFilesBelowHaveToBeInPdfFormat')"
    ></c-info>
    <c-info
      style="max-width: calc(96px * 4)"
      v-else
      class="mt-10"
      :text="$t('theFilesBelowHaveToBeInPdfFormat') + '\n' + $t('pleaseBeAwareThatIfYouNeedToReUploadOneFileYouWillHaveTo').toUpperCase()"
    ></c-info>
    <c-file-input
      :non-native-file-name="registrationCertificateKey ? $t('somePdfUploaded') : ''"
      accept="application/pdf"
      class="mt-8"
      :label-text="$t('registrationCertificate') + ' *'"
      @fileSelected="registrationCertificateSelected"
      ref="cFileInputRegistrationCertificate"
    ></c-file-input>
    <c-file-input
      :non-native-file-name="bankStatementFileKey ? $t('somePdfUploaded') : ''"
      accept="application/pdf"
      class="mt-8"
      :label-text="$t('bankStatement') + ' *'"
      ref="cFileInputBankStatement"
      @fileSelected="bankStatementSelected"
    ></c-file-input>
  </edit-business-page-step-template>
</template>

<script lang="ts">
import EditBusinessPageStepTemplate from "@/components/edit_business_page_view/EditBusinessPageStepTemplate.vue";
import CInput from "@/components/common/CInput.vue";
import validatorMixin from "@/util/validatorMixin";
import CButtonPrimary from "@/components/common/CButtonPrimary.vue";
import CMenu from "@/components/common/CMenu.vue";
import CInfo from "@/components/common/CInfo.vue";
import CFileInput from "@/components/common/CFileInput.vue";
import Vue from "vue";

export default Vue.extend({
  //https://www.legis.md/cautare/getResults?doc_id=109311&lang=ro
  //interpr indiv, cooperative ...
  name: "EditBusinessPageLegalBusinessInformation",
  components: {
    EditBusinessPageStepTemplate,
    CInput,
    CButtonPrimary,
    CMenu,
    CInfo,
    CFileInput
  },
  mixins: [validatorMixin],
  props: {
    isDisabled: {
      type: Boolean
    },
    isEditMode: {
      type: Boolean
    },
    isCreate: {
      type: Boolean
    }
  },
  computed: {
    identificationCode: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessDescription.uniqueIdentificationCode?.toString();
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationUniqueIdentificationCode", value);
      }
    },
    tvaCode: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessDescription.tvaNumber?.toString();
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationTvaNumber", value);
      }
    },
    businessEntityType: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessDescription.businessEntityType;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationBusinessEntityType", value);
      }
    },
    registrationCertificateKey: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessLegalDocuments.registrationCertificateKey;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationRegistrationCertificateKey", value);
      }
    },
    registrationCertificateFileUrl: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessLegalDocuments.registrationCertificateFileUrl;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationRegistrationCertificateFileUrl", value);
      }
    },
    bankStatementFileKey: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessLegalDocuments.bankStatementFileKey;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationBankStatementFileKey", value);
      }
    },
    bankStatementFileUrl: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessLegalDocuments.bankStatementFileUrl;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationBankStatementFileUrl", value);
      }
    }
  },
  data() {
    return {
      tempRegistrationCertificateFile: null,
      tempBankStatementFile: null
    };
  },
  methods: {
    registrationCertificateSelected(registrationCertificate) {
      this.tempRegistrationCertificateFile = registrationCertificate;
      if (this.tempBankStatementFile) this.uploadLegalDocumentsLocal();
    },
    bankStatementSelected(bankStatement) {
      this.tempBankStatementFile = bankStatement;
      if (this.tempRegistrationCertificateFile)
        this.uploadLegalDocumentsLocal();
    },
    uploadLegalDocumentsLocal() {
      this.$store.dispatch("eventModule/showLoadingOverlay", {
        isInstant: true
      });
      this.$store
        .dispatch("businessManagementToolModule/uploadLegalDocuments", {
          registrationCertificate: this.tempRegistrationCertificateFile,
          bankStatement: this.tempBankStatementFile
        })
        .then((response) => {
          this.registrationCertificateKey =
            response.data.registrationCertificateKey;
          this.registrationCertificateFileUrl =
            response.data.registrationCertificateFileUrl;
          this.bankStatementFileKey = response.data.bankStatementFileKey;
          this.bankStatementFileUrl = response.data.bankStatementFileUrl;
        })
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$tc("somethingWentWrongWhileUploadingTheFile", 2),
            type: "error"
          });
          this.$refs.cFileInputRegistrationCertificate.reset();
          this.$refs.cFileInputBankStatement.reset();
          this.tempRegistrationCertificateFile = null;
          this.tempBankStatementFile = null;
          this.$refs.cFileInputRegistrationCertificate.validateInput();
          this.$refs.cFileInputBankStatement.validateInput();
        })
        .finally(() => this.$store.dispatch("eventModule/hideLoadingOverlay"));
    },
    validateLegalDocuments() {
      if (
        this.registrationCertificateKey &&
        this.registrationCertificateFileUrl &&
        this.bankStatementFileKey &&
        this.bankStatementFileUrl
      ) {
        return true;
      } else {
        if (!this.tempRegistrationCertificateFile) {
          this.$refs.cFileInputRegistrationCertificate.reset();
          this.$refs.cFileInputRegistrationCertificate.validateInput();
        }
        if (!this.tempBankStatementFile) {
          this.$refs.cFileInputBankStatement.reset();
          this.$refs.cFileInputBankStatement.validateInput();
        }
        return false;
      }
    },
    handleNextStepClicked() {
      let isIdentificationCodeValid =
        this.$refs.cInputIdentificationCode.validateInput();
      let isTvaCodeValid = this.$refs.cInputTvaCode.validateInput();
      let isLegalDocumentsValid = this.validateLegalDocuments();

      if (isIdentificationCodeValid && isTvaCodeValid && isLegalDocumentsValid)
        this.$emit("nextStepClicked");
    }
  }
});
</script>

<style scoped></style>
