// bachelor-front-react-version-main/src/components/edit-business-page/EditBusinessPageGeneralBusinessInformation.tsx
import { useRef } from "react";
import EditBusinessPageStepTemplate from "./EditBusinessPageStepTemplate";
import { useTranslation } from "react-i18next";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../../store";
import {
  setBusinessApplicationAddress,
  setBusinessApplicationCompanyDescription,
  setBusinessApplicationEmail,
  setBusinessApplicationFacebook,
  setBusinessApplicationInstagram,
  setBusinessApplicationLegalName,
  setBusinessApplicationPhoneNumber,
  setBusinessApplicationWebsite,
  uploadCompanyLogo,
} from "../../store/businessManagementToolSlice";
import CInput from "../common/CInput";
import { validatorHelper } from "../../utils/validatorHelper";
import CTextarea from "../common/CTextarea";
import CFileInput from "../common/CFileInput";
import CButtonPrimary from "../common/CButtonPrimary";
import { showSnackbar } from "../../store/eventSlice";

interface Props {
  isDisabled: boolean;
  isEditMode: boolean;
  stepHeaderClicked: () => void;
  nextStepClicked: () => void;
}

function EditBusinessPageGeneralBusinessInformation(props: Props) {
  const { t } = useTranslation();
  const dispatch = useDispatch();

  const { isDisabled, isEditMode, stepHeaderClicked, nextStepClicked } = props;

  const { legalName, companyDescription } = useSelector(
    // @ts-ignore
    (state: RootState) => state.businessManagementTool.businessApplication.businessDescription
  );
  const { address, website, facebook, instagram, phoneNumber, email } = useSelector(
    // @ts-ignore
    (state: RootState) => state.businessManagementTool.businessApplication.businessContacts || {}
  );
  // @ts-ignore
  const { logoKey, logoFileUrl } = useSelector(
    // @ts-ignore
    (state: RootState) => state.businessManagementTool.businessApplication.businessLogo || {}
  );

  const cInputCompanyNameRef = useRef<any>(null);
  const cTextareaDescriptionRef = useRef<any>(null);
  const cInputAddressRef = useRef<any>(null);
  const cInputPhoneNumberRef = useRef<any>(null);
  const cInputCompanyEmailRef = useRef<any>(null);
  const cFileInputLogoRef = useRef<any>(null);
  const cInputWebsiteUrlRef = useRef<any>(null);
  const cInputFacebookUrlRef = useRef<any>(null);
  const cInputInstagramUrlRef = useRef<any>(null);

  function handleSetBusinessApplicationLegalName(newValue: string) {
    dispatch(setBusinessApplicationLegalName(newValue));
  }

  function handleSetBusinessApplicationCompanyDescription(newValue: string) {
    dispatch(setBusinessApplicationCompanyDescription(newValue));
  }

  function handleSetBusinessApplicationAddress(newValue: string) {
    dispatch(setBusinessApplicationAddress(newValue));
  }

  function handleSetBusinessApplicationWebsite(newValue: string) {
    dispatch(setBusinessApplicationWebsite(newValue));
  }

  function handleSetBusinessApplicationFacebook(newValue: string) {
    dispatch(setBusinessApplicationFacebook(newValue));
  }

  function handleSetBusinessApplicationInstagram(newValue: string) {
    dispatch(setBusinessApplicationInstagram(newValue));
  }

  function handleSetBusinessApplicationPhoneNumber(newValue: string) {
    dispatch(setBusinessApplicationPhoneNumber(newValue));
  }

  function handleSetBusinessApplicationEmail(newValue: string) {
    dispatch(setBusinessApplicationEmail(newValue));
  }

  function handleFileSelected(file: File) {
    // @ts-ignore
    dispatch(uploadCompanyLogo(file)).catch(() => {
      dispatch(
        showSnackbar({
          message: t("somethingWentWrongWhileUploadingTheFile", { count: 1 }),
          type: "error",
        })
      );
      cFileInputLogoRef.current.reset();
      cFileInputLogoRef.current.validateInput();
    });
  }

  function validateLogo(): boolean {
    if (logoKey && logoFileUrl) {
      return true;
    } else {
      cFileInputLogoRef.current.reset();
      return cFileInputLogoRef.current.validateInput();
    }
  }

  function handleNextStepClicked(e?: any) {
    if (e) e.preventDefault();

    let isCompanyNameValid = cInputCompanyNameRef.current.validateInput();
    let isAddressValid = cInputAddressRef.current.validateInput();
    let isPhoneNumberValid = cInputPhoneNumberRef.current.validateInput();
    let isEmailValid = cInputCompanyEmailRef.current.validateInput();
    let isLogoValid = validateLogo();

    if (isCompanyNameValid && isAddressValid && isPhoneNumberValid && isEmailValid && isLogoValid) {
      nextStepClicked();
    }
  }

  return (
    <EditBusinessPageStepTemplate
      stepHeaderClicked={stepHeaderClicked}
      stepNumber={1}
      stepTitle={t("generalBusinessInformation")}
      isDisabled={isDisabled}
      isEditMode={isEditMode}
      actionsEndSlot={
        <div className={"flex flex-row items-center gap-x-8 mt-8 mb-6"}>
          <CButtonPrimary
            iconEnd={["fas", "arrow-right"]}
            size={"medium"}
            text={t("continue")}
            onClick={handleNextStepClicked}></CButtonPrimary>
        </div>
      }>
      <form className="flex flex-col" onSubmit={handleNextStepClicked}>
        <CInput
          validatorFunctions={[validatorHelper.validateRequired]}
          descriptionText={t("doNotIncludeBusinessEntityTypeInformationEtc") || ""}
          labelText={t("companyName") + " *"}
          inputSize="medium"
          ref={cInputCompanyNameRef}
          value={legalName || ""}
          onUpdate={handleSetBusinessApplicationLegalName}></CInput>
        <CTextarea
          className={"mt-8"}
          labelText={t("aboutTheCompany") || ""}
          value={companyDescription || ""}
          onUpdate={handleSetBusinessApplicationCompanyDescription}
          ref={cTextareaDescriptionRef}></CTextarea>
        <CInput
          ref={cInputAddressRef}
          value={address || ""}
          onUpdate={handleSetBusinessApplicationAddress}
          inputSize="medium"
          className={"mt-8"}
          labelText={t("companyAddress") + " *"}
          validatorFunctions={[validatorHelper.validateRequired]}></CInput>
        <CInput
          ref={cInputPhoneNumberRef}
          value={phoneNumber + ""}
          onUpdate={handleSetBusinessApplicationPhoneNumber}
          inputSize="medium"
          className={"mt-8"}
          labelText={t("phoneNumber") + " *"}
          placeholder={t("examplePhoneNumber") || ""}
          validatorFunctions={[validatorHelper.validateIsPhoneNumber, validatorHelper.validateRequired]}></CInput>
        <CInput
          ref={cInputCompanyEmailRef}
          value={email || ""}
          onUpdate={handleSetBusinessApplicationEmail}
          inputSize="medium"
          className={"mt-8"}
          labelText={t("companyEmail") + " *"}
          validatorFunctions={[validatorHelper.validateEmailAddress, validatorHelper.validateRequired]}></CInput>
        <CFileInput
          ref={cFileInputLogoRef}
          onFileSelected={handleFileSelected}
          descriptionText={t("theUpdatedFileHasToBeAnImage") || ""}
          labelText={t("companyLogo") + " *"}
          className={"mt-8"}
          accept="image/png, image/jpeg, image/jpg"
          nonNativeFileName={logoKey ? t("someImageUploaded") || "" : ""}></CFileInput>
        <CInput
          ref={cInputWebsiteUrlRef}
          value={website || ""}
          onUpdate={handleSetBusinessApplicationWebsite}
          inputSize="medium"
          className={"mt-8"}
          labelText={t("companyWebsite") || ""}
          placeholder={t("exampleWebsiteUrl") || ""}></CInput>
        <CInput
          ref={cInputFacebookUrlRef}
          value={facebook || ""}
          onUpdate={handleSetBusinessApplicationFacebook}
          inputSize="medium"
          className={"mt-8"}
          labelText={"Facebook"}
          placeholder={t("exampleFacebookUrl") || ""}></CInput>
        <CInput
          ref={cInputInstagramUrlRef}
          value={instagram || ""}
          onUpdate={handleSetBusinessApplicationInstagram}
          inputSize="medium"
          className={"mt-8"}
          labelText={"Instagram"}
          placeholder={t("exampleInstagramUrl") || ""}></CInput>
      </form>
    </EditBusinessPageStepTemplate>
  );
}

export default EditBusinessPageGeneralBusinessInformation;

// bachelor-front-vue-version-main/src/components/edit_business_page_view/EditBusinessPageGeneralBusinessInformation.vue
<template>
  <edit-business-page-step-template
    @stepHeaderClicked="$emit('stepHeaderClicked')"
    :step-title="$t('generalBusinessInformation')"
    :step-number="1"
    :is-edit-mode="isEditMode"
    :is-disabled="isDisabled"
  >
    <form class="flex flex-col">
      <c-input
        ref="cInputCompanyName"
        v-model="companyName"
        size="medium"
        :label-text="$t('companyName') + ' *'"
        :descriptionText="$t('doNotIncludeBusinessEntityTypeInformationEtc')"
        :validator-functions="[validateRequired]"
      ></c-input>
      <c-textarea
        ref="cTextareaDescription"
        v-model="description"
        :label-text="$t('aboutTheCompany')"
        class="mt-8"
      ></c-textarea>
      <c-input
        ref="cInputAddress"
        v-model="address"
        size="medium"
        class="mt-8"
        :label-text="$t('companyAddress') + ' *'"
        :validator-functions="[validateRequired]"
      ></c-input>
      <c-input
        ref="cInputPhoneNumber"
        v-model="phoneNumber"
        size="medium"
        class="mt-8"
        :label-text="$t('phoneNumber') + ' *'"
        :placeholder="$t('examplePhoneNumber')"
        :validator-functions="[validateIsPhoneNumber, validateRequired]"
      ></c-input>
      <c-input
        ref="cInputCompanyEmail"
        v-model="companyEmail"
        size="medium"
        class="mt-8"
        :label-text="$t('companyEmail') + ' *'"
        :validator-functions="[validateEmailAddress, validateRequired]"
      ></c-input>
      <c-file-input
        :non-native-file-name="logoKey ? $t('someImageUploaded') : ''"
        accept="image/png, image/jpeg, image/jpg"
        class="mt-8"
        :label-text="$t('companyLogo') + ' *'"
        ref="cFileInputLogo"
        @fileSelected="handleFileSelected"
        :description-text="$t('theUpdatedFileHasToBeAnImage')"
      ></c-file-input>
      <c-input
        ref="cInputWebsiteUrl"
        v-model="websiteUrl"
        size="medium"
        class="mt-8"
        :label-text="$t('companyWebsite')"
        :placeholder="$t('exampleWebsiteUrl')"
      ></c-input>
      <c-input
        ref="cInputFacebookUrl"
        v-model="facebookUrl"
        size="medium"
        class="mt-8"
        label-text="Facebook"
        :placeholder="$t('exampleFacebookUrl')"
      ></c-input>
      <c-input
        ref="cInputInstagramUrl"
        v-model="instagramUrl"
        size="medium"
        class="mt-8"
        label-text="Instagram"
        :placeholder="$t('exampleInstagramUrl')"
      ></c-input>
    </form>
    <template #actionsEnd>
      <div class="flex flex-row items-center gap-x-8 mt-8 mb-6">
        <c-button-primary
          size="medium"
          :text="$t('continue')"
          @click="handleNextStepClicked()"
          icon-end="fa-solid fa-arrow-right"
        ></c-button-primary>
      </div>
    </template>
  </edit-business-page-step-template>
</template>

<script>
import EditBusinessPageStepTemplate from "@/components/edit_business_page_view/EditBusinessPageStepTemplate";
import CButtonPrimary from "@/components/common/CButtonPrimary";
import CInput from "@/components/common/CInput";
import validatorMixin from "@/util/validatorMixin";
import CTextarea from "@/components/common/CTextarea";
import CFileInput from "@/components/common/CFileInput";

export default {
  name: "EditBusinessPageGeneralBusinessInformation",
  components: {
    EditBusinessPageStepTemplate,
    CButtonPrimary,
    CInput,
    CTextarea,
    CFileInput
  },
  props: {
    isDisabled: {
      type: Boolean
    },
    isEditMode: {
      type: Boolean
    }
  },
  mixins: [validatorMixin],
  computed: {
    companyName: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessDescription.legalName;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationLegalName", value);
      }
    },
    description: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessDescription.companyDescription;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationCompanyDescription", value);
      }
    },
    address: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessContacts.address;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationAddress", value);
      }
    },
    websiteUrl: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessContacts.website;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationWebsite", value);
      }
    },
    facebookUrl: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessContacts.facebook;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationFacebook", value);
      }
    },
    instagramUrl: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessContacts.instagram;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationInstagram", value);
      }
    },
    phoneNumber: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessContacts.phoneNumber;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationPhoneNumber", value);
      }
    },
    logoKey: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessLogo.logoKey;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationLogoKey", value);
      }
    },
    logoFileUrl: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessLogo.logoFileUrl;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationLogoFileUrl", value);
      }
    },
    companyEmail: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessContacts.email;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationEmail", value);
      }
    }
  },
  methods: {
    handleFileSelected(file) {
      this.$store
        .dispatch("businessManagementToolModule/uploadCompanyLogo", file)
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$tc("somethingWentWrongWhileUploadingTheFile"),
            type: "error"
          });
          this.$refs.cFileInputLogo.reset();
          this.$refs.cFileInputLogo.validateInput();
        });
    },
    validateLogo() {
      if (this.logoKey && this.logoFileUrl) {
        return true;
      } else {
        this.$refs.cFileInputLogo.reset();
        return this.$refs.cFileInputLogo.validateInput();
      }
    },
    handleNextStepClicked() {
      let isCompanyNameValid = this.$refs.cInputCompanyName.validateInput();
      let isAddressValid = this.$refs.cInputAddress.validateInput();
      let isPhoneNumberValid = this.$refs.cInputPhoneNumber.validateInput();
      let isCompanyEmailValid = this.$refs.cInputCompanyEmail.validateInput();
      let isLogoValid = this.validateLogo();

      if (
        isCompanyNameValid &&
        isAddressValid &&
        isPhoneNumberValid &&
        isCompanyEmailValid &&
        isLogoValid
      ) {
        this.$emit("nextStepClicked");
      }
    }
  }
};
</script>

<style scoped></style>
