// bachelor-front-vue-version-main/src/components/edit_business_page_view/EditBusinessPagePaymentDetails.vue
<template>
  <edit-business-page-step-template
    @stepHeaderClicked="$emit('stepHeaderClicked')"
    @nextStepClicked="handleNextStepClicked"
    @previousStepClicked="$emit('previousStepClicked')"
    :step-title="$t('paymentDetails')"
    :step-number="3"
    :is-edit-mode="isEditMode"
    :is-disabled="isDisabled"
  >
    <vc-input
      ref="cInputIban"
      v-model="iban"
      size="medium"
      :label-text="$t('ibanNumber') + ' *'"
      :validator-functions="[validateRequired, validateIsIban]"
      :placeholder="$t('exampleIban')"
    ></vc-input>
    <c-input
      ref="cInputBankName"
      v-model="bankName"
      size="medium"
      class="mt-8"
      :label-text="$t('bankName') + ' *'"
      :validator-functions="[validateRequired]"
    ></c-input>
    <c-input
      ref="cInputSwiftCode"
      v-model="swiftCode"
      size="medium"
      class="mt-8"
      :label-text="$t('swiftCode') + ' *'"
      :placeholder="$t('exampleSwiftCode')"
      :validator-functions="[validateRequired, validateSwiftCode]"
    ></c-input>
  </edit-business-page-step-template>
</template>

<script>
import EditBusinessPageStepTemplate from "@/components/edit_business_page_view/EditBusinessPageStepTemplate";
import CInput from "@/components/common/CInput";
import validatorMixin from "@/util/validatorMixin";

export default {
  name: "EditBusinessPagePaymentDetails",
  components: {
    EditBusinessPageStepTemplate,
    CInput
  },
  mixins: [validatorMixin],
  props: {
    isDisabled: {
      type: Boolean
    },
    isEditMode: {
      type: Boolean
    }
  },
  computed: {
    iban: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessPaymentDetails.iban;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationIban", value);
      }
    },
    swiftCode: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessPaymentDetails.swiftCode;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationSwiftCode", value);
      }
    },
    bankName: {
      get() {
        return this.$store.state.businessManagementToolModule.businessApplication.businessPaymentDetails.bank;
      },
      set(value) {
        this.$store.commit("businessManagementToolModule/setBusinessApplicationBank", value);
      }
    }
  },
  methods: {
    handleNextStepClicked() {
      let isIbanValid = this.$refs.cInputIban.validateInput();
      let isBankNameValid = this.$refs.cInputBankName.validateInput();
      let isSwiftCodeValid = this.$refs.cInputSwiftCode.validateInput();

      if (isIbanValid && isBankNameValid && isSwiftCodeValid)
        this.$emit("nextStepClicked");
    }
  }
};
</script>

<style scoped></style>

// bachelor-front-react-version-main/src/components/edit-business-page/EditBusinessPagePaymentDetails.tsx
import { useRef } from "react";
import EditBusinessPageStepTemplate from "./EditBusinessPageStepTemplate";
import { useTranslation } from "react-i18next";
import { useDispatch, useSelector } from "react-redux";
import { RootState } from "../../store";
import {
  setBusinessApplicationBank,
  setBusinessApplicationIban,
  setBusinessApplicationSwiftCode,
} from "../../store/businessManagementToolSlice";
import CInput from "../common/CInput";
import { validatorHelper } from "../../utils/validatorHelper";

interface Props {
  isDisabled: boolean;
  isEditMode: boolean;
  stepHeaderClicked: () => void;
  nextStepClicked: () => void;
  previousStepClicked: () => void;
}

function EditBusinessPagePaymentDetails(props: Props) {
  const { t } = useTranslation();
  const dispatch = useDispatch();

  const { isDisabled, isEditMode, stepHeaderClicked, nextStepClicked, previousStepClicked } = props;

  const cInputIbanRef = useRef<any>(null);
  const cInputSwiftCodeRef = useRef<any>(null);
  const cInputBankRef = useRef<any>(null);

  // @ts-ignore
  const { iban, swiftCode, bank } = useSelector(
    (state: RootState) => state.businessManagementTool.businessApplication?.businessPaymentDetails
  );

  function handleSetBusinessApplicationIban(newValue: string) {
    dispatch(setBusinessApplicationIban(newValue));
  }

  function handleSetBusinessApplicationSwiftCode(newValue: string) {
    dispatch(setBusinessApplicationSwiftCode(newValue));
  }

  function handleSetBusinessApplicationBank(newValue: string) {
    dispatch(setBusinessApplicationBank(newValue));
  }

  function handleNextStepClicked(e?: any) {
    e?.preventDefault();

    let isIbanValid = cInputIbanRef.current.validateInput();
    let isBankNameValid = cInputBankRef.current.validateInput();
    let isSwiftCodeValid = cInputSwiftCodeRef.current.validateInput();

    if (isIbanValid && isBankNameValid && isSwiftCodeValid) nextStepClicked();
  }

  return (
    <EditBusinessPageStepTemplate
      stepTitle={t("paymentDetails") || ""}
      stepNumber={3}
      isDisabled={isDisabled}
      isEditMode={isEditMode}
      stepHeaderClicked={stepHeaderClicked}
      previousStepClicked={previousStepClicked}
      nextStepClicked={handleNextStepClicked}>
      <form onSubmit={handleNextStepClicked}>
        <CInput
          inputSize={"medium"}
          ref={cInputIbanRef}
          value={iban}
          labelText={t("ibanNumber") + " *"}
          validatorFunctions={[validatorHelper.validateRequired, validatorHelper.validateIsIban]}
          placeholder={t("exampleIban") || ""}
          onUpdate={handleSetBusinessApplicationIban}></CInput>
        <CInput
          inputSize={"medium"}
          ref={cInputBankRef}
          value={bank}
          className={"mt-8"}
          labelText={t("bankName") + " *"}
          validatorFunctions={[validatorHelper.validateRequired]}
          onUpdate={handleSetBusinessApplicationBank}></CInput>
        <CInput
          inputSize={"medium"}
          ref={cInputSwiftCodeRef}
          value={swiftCode}
          className={"mt-8"}
          labelText={t("swiftCode") + " *"}
          placeholder={t("exampleSwiftCode") || ""}
          validatorFunctions={[validatorHelper.validateRequired, validatorHelper.validateSwiftCode]}
          onUpdate={handleSetBusinessApplicationSwiftCode}></CInput>
      </form>
    </EditBusinessPageStepTemplate>
  );
}

export default EditBusinessPagePaymentDetails;
