// bachelor-front-vue-version-main/src/components/edit_business_page_view/EditBusinessPageStepTemplate.vue
<template>
  <div class="flex flex-col">
    <button
      @click="$emit('stepHeaderClicked')"
      :disabled="isDisabled"
      v-if="!isEditMode"
      type="button"
      class="flex self-start flex-row items-center tracking-[unset] hover-no-underline"
      :class="{
        'hover-border-blue hover:text-dark-blue border-mid-gray hover:border-dark-blue':
          !isDisabled,
        'border-spun-pearl text-spun-pearl': isDisabled,
      }"
    >
      <div
        class="w-8 h-8 shrink-0 flex items-center justify-center border border-solid rounded-full"
        style="border-color: inherit !important"
      >
        <h4>{{ stepNumber }}</h4>
      </div>
      <h4
        class="ml-10 text-left"
        :class="{
          underline: !isDisabled,
          'text-spun-pearl': isDisabled,
        }"
      >
        {{ stepTitle }}
      </h4>
    </button>
    <main v-show="isEditMode">
      <header class="flex flex-row items-center gap-x-10 mb-10">
        <div
          class="w-8 h-8 shrink-0 flex items-center justify-center border border-solid rounded-full border-dark-blue text-dark-blue"
        >
          <h4>{{ stepNumber }}</h4>
        </div>
        <h3>{{ stepTitle }}</h3>
      </header>
      <div class="sm:ml-[72px]">
        <slot name="default"></slot>
        <slot name="actionsEnd">
          <div class="flex flex-row items-center gap-x-8 mt-8 mb-6">
            <c-button-secondary
              icon-start="fa-solid fa-arrow-left"
              :text="$t('goBack')"
              @click="$emit('previousStepClicked')"
            ></c-button-secondary>
            <c-button-primary
              size="medium"
              :text="$t('continue')"
              @click="$emit('nextStepClicked')"
              icon-end="fa-solid fa-arrow-right"
            ></c-button-primary>
          </div>
        </slot>
      </div>
    </main>
  </div>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary";
import CButtonPrimary from "@/components/common/CButtonPrimary";

export default {
  name: "EditBusinessPageStepTemplate",
  components: {
    CButtonPrimary,
    CButtonSecondary,
  },
  props: {
    isDisabled: {
      type: Boolean,
      default: false,
    },
    stepNumber: {
      type: Number,
      required: true,
    },
    stepTitle: {
      type: String,
      required: true,
    },
    isEditMode: {
      type: Boolean,
      default: false,
    },
  },
};
</script>

<style scoped>
.hover-no-underline:hover h4 {
  text-decoration: none !important;
}

.hover-border-blue:hover div {
  border-color: var(--dark-blue) !important;
}
</style>

// bachelor-front-react-version-main/src/components/edit-business-page/EditBusinessPageStepTemplate.tsx
import classNames from "classnames";
import { ReactNode } from "react";
import CButtonSecondary from "../common/CButtonSecondary";
import { useTranslation } from "react-i18next";
import "../../assets/styles/EditBusinessPageStepTemplate.scss";

interface Props {
  isDisabled: boolean;
  isEditMode: boolean;
  stepNumber: number;
  stepTitle: string;
  stepHeaderClicked?: () => void;
  previousStepClicked?: () => void;
  nextStepClicked?: () => void;
  children?: ReactNode;
  actionsEndSlot?: ReactNode;
}

function EditBusinessPageStepTemplate(props: Props) {
  const { t } = useTranslation();

  const {
    isDisabled,
    isEditMode,
    stepNumber,
    stepTitle,
    stepHeaderClicked,
    previousStepClicked,
    nextStepClicked,
    children,
    actionsEndSlot,
  } = props;

  return (
    <div className="flex flex-col" data-css="EditBusinessPageStepTemplate">
      {!isEditMode && (
        <button
          type="button"
          className={classNames({
            "hover-border-blue hover:text-dark-blue border-mid-gray hover:border-dark-blue": !isDisabled,
            "border-spun-pearl text-spun-pearl": isDisabled,
            "flex self-start flex-row items-center tracking-[unset] hover-no-underline": true,
          })}
          onClick={stepHeaderClicked}
          disabled={isDisabled}>
          <div
            style={{ borderColor: "inherit !important" }}
            className={"w-8 h-8 shrink-0 flex items-center justify-center border border-solid rounded-full"}>
            <h4>{stepNumber}</h4>
          </div>
          <h4
            className={classNames({
              underline: !isDisabled,
              "text-spun-pearl": isDisabled,
              "ml-10 text-left": true,
            })}>
            {stepTitle}
          </h4>
        </button>
      )}
      {isEditMode && (
        <div>
          <header className="flex flex-row items-center gap-x-10 mb-10">
            <div className="w-8 h-8 shrink-0 flex items-center justify-center border border-solid rounded-full border-dark-blue text-dark-blue">
              <h4>{stepNumber}</h4>
            </div>
            <h3>{stepTitle}</h3>
          </header>
          <div className="sm:ml-[72px]">
            {children}
            {actionsEndSlot || (
              <div className="flex flex-row items-center gap-x-8 mt-8 mb-6">
                <CButtonSecondary
                  onClick={previousStepClicked}
                  iconStart={["fas", "arrow-left"]}
                  text={t("goBack")}></CButtonSecondary>
                <CButtonSecondary
                  size="medium"
                  onClick={nextStepClicked}
                  iconStart={["fas", "arrow-right"]}
                  text={t("continue")}></CButtonSecondary>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export default EditBusinessPageStepTemplate;
