// bachelor-front-react-version-main/src/components/account/DiscussionWithAdministratorDialog.tsx
import { useEffect, useRef, useState } from "react";
import { SupportThread, ThreadReply } from "../../generated-sources/openapi";
import { hideLoadingOverlay, showLoadingOverlay, showSnackbar } from "../../store/eventSlice";
import { useDispatch } from "react-redux";
import { useTranslation } from "react-i18next";
import { closeSupportThread, createThreadReply, fetchMessages } from "../../store/userSlice";
import CDialog from "../common/CDialog";
import CComment from "../common/CComment";
import { dateFormatterHelper } from "../../utils/dateFormatterHelper";
import CTextarea from "../common/CTextarea";
import { validatorHelper } from "../../utils/validatorHelper";
import CButtonSecondary from "../common/CButtonSecondary";
import CButtonPrimary from "../common/CButtonPrimary";

interface Props {
  isDialogShown: boolean;
  onClose: () => void;
  discussionWithAdministratorDialogThreadInfo: SupportThread | null;
}

function DiscussionWithAdministratorDialog(props: Props) {
  const { t } = useTranslation();
  const dispatch = useDispatch();

  const { isDialogShown, onClose, discussionWithAdministratorDialogThreadInfo } = props;

  const [newMessage, setNewMessage] = useState("");
  const [isConfirmDeleteDialogShown, setIsConfirmDeleteDialogShown] = useState(false);
  const [isReplyLoading, setIsReplyLoading] = useState(false);

  const [messages, setMessages] = useState<ThreadReply[]>([]);
  const [fakeWebsocket, setFakeWebsocket] = useState<any>(null);

  const cTextareaNewMessageRef = useRef(null);

  useEffect(() => {
    if (isDialogShown) {
      dispatch(showLoadingOverlay({ isInstant: false }));
      fetchMessagesLocal().finally(() => dispatch(hideLoadingOverlay()));
      startFakeWebsocket();
    } else {
      stopFakeWebsocket();
      reset();
    }
  }, [isDialogShown]);

  function scrollToLastItem() {
    setTimeout(() => {
      document.getElementById("target-last-item")?.scrollIntoView({ behavior: "smooth" });
    }, 0);
  }

  function reset() {
    setNewMessage("");
    setIsConfirmDeleteDialogShown(false);
    setIsReplyLoading(false);
    setMessages([]);
    setFakeWebsocket(null);
  }

  function handleCloseIssue() {
    setIsConfirmDeleteDialogShown(true);
  }

  function closeIssue() {
    // @ts-ignore
    dispatch(closeSupportThread({ supportThreadId: discussionWithAdministratorDialogThreadInfo.supportThreadId })).then(
      () => onClose()
    );
  }

  function startFakeWebsocket() {
    setFakeWebsocket(
      setInterval(() => {
        fetchMessagesLocal(false);
      }, 10000)
    );
  }

  function stopFakeWebsocket() {
    clearInterval(fakeWebsocket);
  }

  function handleSendNewMessage() {
    // @ts-ignore
    let isMessageValid = cTextareaNewMessageRef.current.validateInput();
    if (isMessageValid) {
      setIsReplyLoading(true);
      dispatch(
        // @ts-ignore
        createThreadReply({
          // @ts-ignore
          supportThreadId: discussionWithAdministratorDialogThreadInfo.supportThreadId,
          text: newMessage,
        })
      )
        .then(() => setNewMessage(""))
        .catch(() =>
          dispatch(
            showSnackbar({
              message: t("failedToPostMessage"),
              type: "error",
            })
          )
        )
        .finally(() => {
          setIsReplyLoading(false);
          fetchMessagesLocal();
        });
    }
  }

  function fetchMessagesLocal(scrollIntoView = true) {
    // @ts-ignore
    return dispatch(fetchMessages(discussionWithAdministratorDialogThreadInfo.supportThreadId))
      .then((response: any) => {
        setMessages(response.data.ThreadReplyPageList);
        if (messages.length && scrollIntoView) {
          scrollToLastItem();
        }
      })
      .catch(() => {
        dispatch(
          showSnackbar({
            message: t("failedToFetchMessages"),
            type: "error",
          })
        );
      });
  }

  return (
    <CDialog isShown={isDialogShown} onUpdate={(val) => (val ? {} : onClose)} footerSlot={<div></div>}>
      <CDialog
        isShown={isConfirmDeleteDialogShown}
        onUpdate={setIsConfirmDeleteDialogShown}
        onConfirm={closeIssue}
        subtitleText={t("deleteDiscussionSubtitle") || ""}
        titleText={t("deleteDiscussion") || ""}></CDialog>
      <div className="flex flex-col">
        <div className="border-solid border-b border-mid-gray flex-col sticky top-0 bg-white">
          {discussionWithAdministratorDialogThreadInfo && (
            <CComment
              className={"px-8 mb-3"}
              isReplyEnabled={false}
              authorSlot={() => t("askedByYou")}
              textSlot={discussionWithAdministratorDialogThreadInfo.threadTopic}
              dateSlot={dateFormatterHelper.getFormattedDateTime(
                discussionWithAdministratorDialogThreadInfo.createdDate || ""
              )}></CComment>
          )}
        </div>
        {messages.map((message, index) => (
          <CComment
            className={"ml-12 px-8"}
            key={message.threadReplyId}
            isReplyEnabled={false}
            messageObject={message}
            authorSlot={(author: any) => (author.isCreatorOfTheThread ? t("you") : t("administrator"))}></CComment>
        ))}
        {!messages.length && (
          <div className={"flex flex-col grow min-h-[144px] items-center justify-center mt-6"}>
            <h4 className="text-spun-pearl">{t("noMessages")}</h4>
          </div>
        )}
        <div id="target-last-item"></div>
        <div className="pb-4 sticky bottom-0 bg-white mt-6 pt-3 border-t border-solid border-mid-gray">
          <div className="ml-12 flex flex-col px-8">
            <CTextarea
              isDisabled={isReplyLoading}
              grow={true}
              ref={cTextareaNewMessageRef}
              value={newMessage}
              onUpdate={setNewMessage}
              rows={2}
              validateOnBlur={false}
              validatorFunctions={[validatorHelper.validateRequired]}
              placeholder={t("typeANewMessage") || ""}
              size={"small"}></CTextarea>
            <div className="flex flex-row justify-end gap-6 mt-3 items-center flex-wrap">
              <CButtonSecondary onClick={handleCloseIssue} text={t("closeIssue")}></CButtonSecondary>
              <CButtonSecondary onClick={onClose} text={t("exitDialog")}></CButtonSecondary>
              <CButtonPrimary
                iconEnd={["fas", "paper-plane"]}
                className={"self-end"}
                onClick={handleSendNewMessage}
                text={t("send")}
                isDisabled={isReplyLoading}></CButtonPrimary>
            </div>
          </div>
        </div>
      </div>
    </CDialog>
  );
}

export default DiscussionWithAdministratorDialog;

// bachelor-front-vue-version-main/src/components/account_view/DiscussionWithAdministratorDialog.vue
<template>
  <c-dialog width="644"
            content-class-overwrite="border border-mid-gray border-solid bg-white focus-visible:outline-none flex flex-col"
            :is-shown="isDialogShown" @update="(e) => !e ? $emit('close') : {}">
    <template #body>
      <c-dialog :title="$t('deleteDiscussion')"
                @confirm="closeIssue()" :subtitle-text="$t('deleteDiscussionSubtitle')"
                v-model="isConfirmDeleteDialogShown"></c-dialog>
      <div class="flex flex-col">
        <div class="border-solid border-b border-mid-gray flex-col sticky top-0 bg-white">
          <c-comment class="px-8 mb-3" v-if="threadInfo" :is-reply-enabled="false">
            <template #author>
              {{ $t("askedByYou") }}
            </template>
            <template #date>
              {{ getFormattedDateTime(threadInfo.createdDate) }}
            </template>
            <template #text>
              {{ threadInfo.threadTopic }}
            </template>
          </c-comment>
        </div>
        <c-comment class="ml-12 px-8" v-for="(message) in messages" :key="message.threadReplyId"
                   :is-reply-enabled="false"
                   :message-object="message">
          <template #author="{author}">
            {{ author.isCreatorOfTheThread ? $t("you") : $t("administrator") }}
          </template>
        </c-comment>
        <div v-if="!messages.length" class="flex flex-col grow min-h-[144px] items-center justify-center mt-6">
          <h4 class="text-spun-pearl">{{ $t("noMessages") }}</h4>
        </div>
        <div id="target-last-item"></div>
        <div class="pb-4 sticky bottom-0 bg-white mt-6 pt-3 border-t border-solid border-mid-gray">
          <div class="ml-12 flex flex-col px-8">
            <c-textarea :is-disabled="isReplyLoading" grow ref="cTextareaNewMessage" size="small" v-model="newMessage"
                        :rows="2"
                        data-cy="new-message-textarea"
                        :validate-on-blur="false" :validator-functions="[validateRequired]"
                        :placeholder="$t('typeANewMessage')"></c-textarea>
            <div class="flex flex-row justify-end gap-6 mt-3 items-center flex-wrap">
              <c-button-secondary data-cy="close-issue-button" @click="handleCloseIssue()" :text="$t('closeIssue')"></c-button-secondary>
              <c-button-secondary @click="$emit('close')" :text="$t('exitDialog')"></c-button-secondary>
              <c-button-primary :is-disabled="isReplyLoading" @click="handleSendNewMessage()"
                                icon-end="fa-solid fa-paper-plane"
                                class="self-end"
                                data-cy="send-message-button"
                                :text="$t('send')"></c-button-primary>
            </div>
          </div>
        </div>
      </div>
    </template>
    <template #footer>
      <div></div>
    </template>
  </c-dialog>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary.vue";
import CTextarea from "@/components/common/CTextarea.vue";
import CDialog from "@/components/common/CDialog.vue";
import CButtonPrimary from "@/components/common/CButtonPrimary.vue";
import CComment from "@/components/common/CComment.vue";
import dateFormatterMixin from "@/util/dateFormatterMixin";
import validatorMixin from "@/util/validatorMixin";

export default {
  name: "DiscussionWithAdministratorDialog",
  mixins: [dateFormatterMixin, validatorMixin],
  props: {
    isDialogShown: {
      type: Boolean,
      required: true
    }
  },
  watch: {
    isDialogShown(newValue) {
      if (newValue) {
        this.$store.dispatch("eventModule/showLoadingOverlay");
        this.fetchMessagesLocal()
          .finally(() => {
            this.$store.dispatch("eventModule/hideLoadingOverlay");
          });
        this.startFakeWebsocket();
      } else {
        this.stopFakeWebsocket();
        this.reset();
      }
    }
  },
  components: {
    CComment,
    CDialog,
    CTextarea,
    CButtonSecondary,
    CButtonPrimary
  },
  data() {
    return {
      newMessage: "",
      threadInfo: null,
      isConfirmDeleteDialogShown: false,

      isReplyLoading: false,
      messages: [],

      fakeWebsocket: null
    };
  },
  methods: {
    scrollToLastItem() {
      setTimeout(() => {
        document.getElementById("target-last-item")?.scrollIntoView({ behavior: "smooth" });
      }, 0);
    },
    reset() {
      this.newMessage = "";
      this.threadInfo = null;
      this.isConfirmDeleteDialogShown = false;

      this.isReplyLoading = false;
      this.messages = [];
    },
    handleCloseIssue() {
      this.isConfirmDeleteDialogShown = true;
    },
    closeIssue() {
      this.$store.dispatch("userModule/closeSupportThread", { supportThreadId: this.threadInfo.supportThreadId })
        .then(() => {
          this.$emit("close");
        });
    },
    handleSendNewMessage() {
      let isMessageValid = this.$refs.cTextareaNewMessage.validateInput();
      if (isMessageValid) {
        this.isReplyLoading = true;
        this.$store.dispatch("userModule/createThreadReply", {
          supportThreadId: this.threadInfo.supportThreadId,
          text: this.newMessage
        })
          .then(() => {
            this.newMessage = "";
          })
          .catch(() => {
            this.$store.dispatch("eventModule/showSnackbar", {
              message: this.$t("failedToPostMessage"),
              type: "error"
            });
          })
          .finally(() => {
            this.isReplyLoading = false;
            this.fetchMessagesLocal();
          });
      }
    },
    fetchMessagesLocal(scrollIntoView = true) {
      return this.$store.dispatch("userModule/fetchMessages", this.threadInfo.supportThreadId)
        .then((response) => {
          this.messages = this.messages = response.data.ThreadReplyPageList;
          if (this.messages.length && scrollIntoView) {
            this.scrollToLastItem();
          }
        })
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$t("failedToFetchMessages"),
            type: "error"
          });
        });
    },
    startFakeWebsocket() {
      this.fakeWebsocket = setInterval(() => {
        this.fetchMessagesLocal(false);
      }, 10000);
    },
    stopFakeWebsocket() {
      clearInterval(this.fakeWebsocket);
    }
  }
};
</script>

<style scoped>

</style>
