// bachelor-front-react-version-main/src/components/administrator-management-tool/AdministratorOrderListItem.tsx
import {
  OrderStatus,
  OrderToFulfill,
  PatchOrderToFulfillProductStatusRequest,
  PatchOrderToFulfillStatusRequest,
  ProductInOrder,
} from "../../generated-sources/openapi";
import "../../assets/styles/AdministratorOrderListItem.scss";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { dateFormatterHelper } from "../../utils/dateFormatterHelper";
import CButtonSecondary from "../common/CButtonSecondary";
import CDialog from "../common/CDialog";
import CMenu from "../common/CMenu";
import CButtonPrimary from "../common/CButtonPrimary";
import ProductItemFromOrder from "../order/ProductItemFromOrder";
import { useTranslation } from "react-i18next";
import { useDispatch } from "react-redux";
import { useState } from "react";
import { stringFormatterHelper } from "../../utils/stringFormatterHelper";
import { updateOrderStatus, updateProductStatus } from "../../store/administratorManagementToolSlice";

interface Props {
  order: OrderToFulfill;
}

function AdministratorOrderListItem(props: Props) {
  const dispatch = useDispatch();
  const { t } = useTranslation();

  const { order } = props;

  const [isOrderDetailsDialogShown, setIsOrderDetailsDialogShown] = useState(false);

  function getFormattedFullPrice() {
    let fullPrice = 0;
    (order.productList || []).forEach((product) => {
      fullPrice += (product.price || 0) * (product.amount || 0);
    });
    return stringFormatterHelper.getFormattedPrice(fullPrice);
  }

  function getAvailableOrderStatuses() {
    let availableOrderStatuses = Object.values(OrderStatus);
    return availableOrderStatuses.map((status: string) => {
      return {
        text: getFormattedStatus(status),
        value: status,
        selected: order.orderStatus === status,
        function: () => {
          if (order.orderStatus !== status) {
            let patchOrderToFulfillStatusRequest: PatchOrderToFulfillStatusRequest = {
              orderId: order.id || "",
              // @ts-ignore
              status: status,
            };
            // @ts-ignore
            dispatch(updateOrderStatus(patchOrderToFulfillStatusRequest));
          }
        },
      };
    });
  }

  function getAvailableProductStatuses(product: ProductInOrder) {
    let availableOrderStatuses = Object.values(OrderStatus);
    return availableOrderStatuses.map((status: string) => {
      return {
        text: getFormattedStatus(status),
        value: status,
        selected: product.orderStatus === status,
        function: () => {
          if (product.orderStatus !== status) {
            let patchOrderToFulfillProductStatusRequest: PatchOrderToFulfillProductStatusRequest = {
              orderId: order.id || "",
              productId: product.id || "",
              // @ts-ignore
              status: status,
            };
            // @ts-ignore
            dispatch(updateProductStatus(patchOrderToFulfillProductStatusRequest));
          }
        },
      };
    });
  }

  function getFormattedStatus(status: string): string {
    return t(stringFormatterHelper.underscoreToCamelCase(status.toLowerCase()));
  }

  return (
    <div
      data-css="AdministratorOrderListItem"
      className={"h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between"}>
      <div className="flex flex-row items-center gap-4">
        <FontAwesomeIcon
          className={"text-mid-gray"}
          title={getFormattedStatus(order.orderStatus || "")}
          icon={["fas", "truck"]}></FontAwesomeIcon>
        <span className="c-text-14 truncate">
          {t("orderFrom") + " " + dateFormatterHelper.getFormattedDateTime(new Date(order.createdDate || ""))}
        </span>
        <CButtonSecondary onClick={() => setIsOrderDetailsDialogShown(true)} text={t("seeDetails")}></CButtonSecondary>
        <CDialog
          width={"lg"}
          isShown={isOrderDetailsDialogShown}
          onUpdate={setIsOrderDetailsDialogShown}
          titleSlot={
            <h3>
              {t("orderFrom") + " " + dateFormatterHelper.getFormattedDateTime(new Date(order.createdDate || ""))}
            </h3>
          }
          footerSlot={
            <div className="mt-6 flex items-center justify-end">
              <CButtonSecondary
                onClick={() => setIsOrderDetailsDialogShown(false)}
                text={t("close")}></CButtonSecondary>
            </div>
          }>
          <div className="flex flex-col">
            <h4 className="mt-8">{t("generalOrderInformation")}</h4>
            <table className="mt-4">
              <tbody>
                <tr>
                  <td className="sm:w-[30%]">
                    <p>{t("orderDate")}</p>
                  </td>
                  <td>
                    <span className="label block">
                      {dateFormatterHelper.getFormattedDateTime(new Date(order.createdDate || ""))}
                    </span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>{t("status")}</p>
                  </td>
                  <td>
                    <CMenu isRadio={true} items={getAvailableOrderStatuses()}>
                      <CButtonPrimary
                        type="button"
                        text={getFormattedStatus(order.orderStatus || "")}
                        iconEnd={["fas", "chevron-down"]}></CButtonPrimary>
                    </CMenu>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>{t("totalPrice")}</p>
                  </td>
                  <td>
                    <span className="label block">{getFormattedFullPrice()}</span>
                  </td>
                </tr>
              </tbody>
            </table>
            <h4 className="mt-8">{t("shippingDetails")}</h4>
            <table className="mt-4">
              <tbody>
                <tr>
                  <td className="sm:w-[30%]">
                    <p>{t("city")}</p>
                  </td>
                  <td>
                    <span className="label block">{order.shippingDetails?.city}</span>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>{t("address")}</p>
                  </td>
                  <td>
                    <a href={"https://maps.google.com/?q=" + order.shippingDetails?.address} target="_blank">
                      <CButtonSecondary
                        text={order.shippingDetails?.address || ""}
                        className="text-start"
                        size="medium"></CButtonSecondary>
                    </a>
                  </td>
                </tr>
                <tr>
                  <td>
                    <p>{t("postalCode")}</p>
                  </td>
                  <td>
                    <span className="label block">{order.shippingDetails?.postalCode}</span>
                  </td>
                </tr>
              </tbody>
            </table>
            <h4 className="mt-8">{t("orderedProducts")}</h4>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-4">
              {order.productList?.map((product) => (
                <ProductItemFromOrder product={product} key={product.id}>
                  <CMenu isRadio={true} items={getAvailableProductStatuses(product)}>
                    <CButtonPrimary
                      type="button"
                      text={getFormattedStatus(product.orderStatus || "")}
                      iconEnd={["fas", "chevron-down"]}></CButtonPrimary>
                  </CMenu>
                </ProductItemFromOrder>
              ))}
            </div>
          </div>
        </CDialog>
      </div>
    </div>
  );
}

export default AdministratorOrderListItem;

// bachelor-front-vue-version-main/src/components/administrator_management_tool_view/AdministratorOrderListItem.vue
<template>
  <div class="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
    <div class="flex flex-row items-center gap-4">
      <font-awesome-icon :title="getFormattedStatus(order.orderStatus)" icon="fa-solid fa-truck"
                         class="text-mid-gray"></font-awesome-icon>
      <span class="c-text-14 truncate">{{ $t("orderFrom") + " " + getFormattedDateTime(new Date(order.createdDate))
        }}</span>
    </div>
    <c-button-secondary @click="isOrderDetailsDialogShown = true" :text="$t('seeDetails')"></c-button-secondary>
    <c-dialog v-model="isOrderDetailsDialogShown" width="1000">
      <template #title>
        <h3>{{ $t("orderFrom") + " " + getFormattedDateTime(new Date(order.createdDate)) }}</h3>
      </template>
      <template #body>
        <div class="flex flex-col">
          <h4 class="mt-8">{{ $t("generalOrderInformation") }}</h4>
          <table class="mt-4">
            <tbody>
            <tr>
              <td class="sm:w-[30%]"><p>{{ $t("orderDate") }}</p></td>
              <td><span class="label block">{{ getFormattedDateTime(new Date(order.createdDate)) }}</span></td>
            </tr>
            <tr>
              <td><p>{{ $t("status") }}</p></td>
              <td>
                <c-menu is-radio :items="availableOrderStatuses">
                  <template #activator>
                    <c-button-primary icon-end="fa-solid fa-chevron-down" type="button"
                                      :text="getFormattedStatus(order.orderStatus)">
                    </c-button-primary>
                  </template>
                </c-menu>
              </td>
            </tr>
            <tr>
              <td><p>{{ $t("totalPrice") }}</p></td>
              <td><span class="label block">{{ formattedFullPrice }}</span></td>
            </tr>
            </tbody>
          </table>
          <h4 class="mt-8">{{ $t("shippingDetails") }}</h4>
          <table class="mt-4">
            <tbody>
            <tr>
              <td class="sm:w-[30%]"><p>{{ $t("city") }}</p></td>
              <td><span class="label block">{{ order.shippingDetails.city }}</span></td>
            </tr>
            <tr>
              <td><p>{{ $t("address") }}</p></td>
              <td>
                <a :href="'https://maps.google.com/?q=' + order.shippingDetails.address" target="_blank">
                  <c-button-secondary
                    class="text-start"
                    size="medium"
                    :text="order.shippingDetails.address"
                  ></c-button-secondary>
                </a>
              </td>
            </tr>
            <tr>
              <td><p>{{ $t("postalCode") }}</p></td>
              <td><span class="label block">{{ order.shippingDetails.postalCode }}</span></td>
            </tr>
            </tbody>
          </table>
          <h4 class="mt-8">{{ $t("orderedProducts") }}</h4>
          <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-4">
            <product-item-from-order v-for="product in order.productList" :key="product.id"
                                     :product="product">
              <template #status>
                <c-menu
                  is-radio :items="getAvailableProductStatuses(product)">
                  <template #activator>
                    <c-button-primary icon-end="fa-solid fa-chevron-down" type="button"
                                      :text="getFormattedStatus(product.orderStatus)">
                    </c-button-primary>
                  </template>
                </c-menu>
              </template>
            </product-item-from-order>
          </div>
        </div>
      </template>
      <template #footer>
        <div class="mt-6 flex items-center justify-end">
          <c-button-secondary @click="isOrderDetailsDialogShown = false" :text="$t('close')"></c-button-secondary>
        </div>
      </template>
    </c-dialog>
  </div>
</template>

<script lang="ts">
import CButtonSecondary from "@/components/common/CButtonSecondary.vue";
import { stringFormatter } from "@/util/stringFormatter";
import Vue from "vue";
import dateFormatterMixin from "@/util/dateFormatterMixin";
import CButtonPrimary from "@/components/common/CButtonPrimary.vue";
import CDialog from "@/components/common/CDialog.vue";
import ProductItemFromOrder from "@/components/order_view/ProductItemFromOrder.vue";
import CMenu from "@/components/common/CMenu.vue";
import {
  OrderStatus,
  PatchOrderToFulfillProductStatusRequest,
  PatchOrderToFulfillStatusRequest,
  ProductInOrder
} from "@/generated-sources/openapi";

export default Vue.extend({
  name: "AdministratorOrderListItem",
  components: {
    CButtonSecondary,
    CButtonPrimary,
    CDialog,
    ProductItemFromOrder,
    CMenu
  },
  mixins: [dateFormatterMixin],
  props: {
    order: {
      type: Object,
      required: true
    }
  },
  computed: {
    formattedFullPrice() {
      let fullPrice = 0;
      this.order.productList.forEach((product: { price: number; amount: number; }) => {
        fullPrice += product.price * product.amount;
      });
      return stringFormatter.getFormattedPrice(fullPrice);
    },
    availableOrderStatuses() {
      let availableOrderStatuses = Object.values(OrderStatus);
      return availableOrderStatuses.map((status: string) => {
        return {
          name: this.getFormattedStatus(status),
          value: status,
          selected: this.order.orderStatus === status,
          function: () => {
            if (this.order.orderStatus !== status) {
              let patchOrderToFulfillStatusRequest: PatchOrderToFulfillStatusRequest = {
                orderId: this.order.id,
                status: status
              };
              this.$store.dispatch("administratorManagementToolModule/updateOrderStatus", patchOrderToFulfillStatusRequest);
            }
          }
        };
      });
    }
  },
  data() {
    return {
      isOrderDetailsDialogShown: false
    };
  },
  methods: {
    getFormattedStatus(status: string): string {
      return this.$t(stringFormatter.underscoreToCamelCase(status.toLowerCase()));
    },
    getAvailableProductStatuses(product: ProductInOrder) {
      let availableOrderStatuses = Object.values(OrderStatus);
      return availableOrderStatuses.map((status: string) => {
        return {
          name: this.getFormattedStatus(status),
          value: status,
          selected: product.orderStatus === status,
          function: () => {
            if (product.orderStatus !== status) {
              let patchOrderToFulfillProductStatusRequest: PatchOrderToFulfillProductStatusRequest = {
                orderId: this.order.id,
                productId: product.id,
                status: status
              };
              this.$store.dispatch("administratorManagementToolModule/updateProductStatus", patchOrderToFulfillProductStatusRequest);
            }
          }
        };
      });
    }
  }
});
</script>

<style scoped>
td p:first-child {
  @apply pr-10;
}

table td {
  border-top: 8px solid transparent;
  vertical-align: top;
}

table tr:first-child td {
  border-top: 0;
}
</style>
