// bachelor-front-react-version-main/src/components/administrator-management-tool/BusinessPageListItemProductListItem.tsx
import { Product } from "../../generated-sources/openapi";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { deleteProduct } from "../../store/administratorManagementToolSlice";
import { showSnackbar } from "../../store/eventSlice";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import CButtonSecondary from "../common/CButtonSecondary";
import CDialog from "../common/CDialog";

interface Props {
  onProductDeleted: () => void;
  product: Product;
}

function BusinessPageListItemProductListItem(props: Props) {
  const dispatch = useDispatch();
  const { t } = useTranslation();

  const { onProductDeleted, product } = props;

  const [isDeleteProductDialogShown, setIsDeleteProductDialogShown] = useState(false);

  function handleConfirmDeleteProduct() {
    // @ts-ignore
    dispatch(deleteProduct(product.id))
      .then(() => {
        onProductDeleted();
        setIsDeleteProductDialogShown(false);
      })
      .catch(() =>
        dispatch(
          showSnackbar({
            message: t("somethingWentWrong"),
            type: "error",
          })
        )
      );
  }

  return (
    <div className="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
      <span className="c-text-14 truncate">{product.name}</span>
      <div className="flex items-center gap-x-3 flex-wrap">
        <Link target="_blank" to={"/product/" + product.id}>
          <CButtonSecondary text={t("view")} />
        </Link>
        <CButtonSecondary text={t("delete")} onClick={() => setIsDeleteProductDialogShown(true)} />
        <CDialog
          isShown={isDeleteProductDialogShown}
          onUpdate={setIsDeleteProductDialogShown}
          titleText={t("deleteProduct") || ""}
          onConfirm={handleConfirmDeleteProduct}
          subtitleText={t("doYouReallyWantToDelete", { name: product.name }) || ""}></CDialog>
      </div>
    </div>
  );
}

export default BusinessPageListItemProductListItem;

// bachelor-front-vue-version-main/src/components/administrator_management_tool_view/BusinessPageListItemProductListItem.vue
<template>
  <div class="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
    <span class="c-text-14 truncate">{{ product.name }}</span>
    <div class="flex items-center gap-x-3 flex-wrap">
      <router-link target="_blank" :to="{name: 'product', params: {productId: product.id}}">
        <c-button-secondary :text="$t('view')"></c-button-secondary>
      </router-link>
      <c-button-secondary @click="isDeleteProductDialogShown = true" :text="$t('delete')"></c-button-secondary>
      <c-dialog :title-text="$t('deleteProduct')" :subtitle-text="$t('doYouReallyWantToDelete', {name: product.name})"
                v-model="isDeleteProductDialogShown" @confirm="handleConfirmDeleteProduct()"></c-dialog>
    </div>
  </div>
</template>

<script>
import CDialog from "@/components/common/CDialog";
import CButtonSecondary from "@/components/common/CButtonSecondary";

export default {
  name: "BusinessPageListItemProductListItem",
  components: {
    CButtonSecondary,
    CDialog
  },
  props: {
    product: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      isDeleteProductDialogShown: false
    };
  },
  methods: {
    handleConfirmDeleteProduct() {
      this.$store.dispatch("administratorManagementToolModule/deleteProduct", this.product.id)
        .then(() => {
          this.$emit("productDeleted");
          this.isDeleteProductDialogShown = false;
        })
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$t("somethingWentWrong"),
            type: "error"
          });
        });
    }
  }
};
</script>

<style scoped>

</style>
