// bachelor-front-react-version-main/src/components/administrator-management-tool/CategoryListItem.tsx
import { Category } from "../../generated-sources/openapi";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { useTranslation } from "react-i18next";
import { deleteCategory, fetchCategories } from "../../store/administratorManagementToolSlice";
import { showSnackbar } from "../../store/eventSlice";
import { Link } from "react-router-dom";
import CButtonSecondary from "../common/CButtonSecondary";
import CDialog from "../common/CDialog";

interface Props {
  category: Category;
}

function CategoryListItem(props: Props) {
  const dispatch = useDispatch();
  const { t } = useTranslation();

  const { category } = props;

  const [isDeleteCategoryDialogShown, setIsDeleteCategoryDialogShown] = useState(false);

  function handleConfirmDeleteCategory() {
    // @ts-ignore
    dispatch(deleteCategory(category.id))
      .then(() => {
        setIsDeleteCategoryDialogShown(false);
        // @ts-ignore
        dispatch(fetchCategories(1));
      })
      .catch(() =>
        dispatch(
          showSnackbar({
            message: t("somethingWentWrong"),
            type: "error",
          })
        )
      );
  }

  return (
    <div className="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
      <span className="c-text-14 truncate">{t((category.category || "").toLowerCase())}</span>
      <div className="flex items-center gap-x-3 flex-wrap">
        <Link
          target="_blank"
          to={{
            pathname: "/",
            search: new URLSearchParams({ categories: category.id ?? "" }).toString(),
          }}>
          <CButtonSecondary text={t("viewProducts")} />
        </Link>
        <CButtonSecondary text={t("delete")} onClick={() => setIsDeleteCategoryDialogShown(true)} />
      </div>
      <CDialog
        subtitleText={t("doYouReallyWantToDelete", { name: t((category.category || "").toLowerCase()) }) || ""}
        titleText={t("deleteCategory") || ""}
        isShown={isDeleteCategoryDialogShown}
        onConfirm={handleConfirmDeleteCategory}
        onUpdate={setIsDeleteCategoryDialogShown}></CDialog>
    </div>
  );
}

export default CategoryListItem;

// bachelor-front-vue-version-main/src/components/administrator_management_tool_view/CategoryListItem.vue
<template>
  <div class="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
    <span class="c-text-14 truncate">{{ $t(category.category.toLowerCase()) }}</span>
    <div class="flex items-center gap-x-3 flex-wrap">
      <router-link target="_blank" :to="{name: 'base', query: {categories: category.id}}">
        <c-button-secondary
          :text="$t('viewProducts')"
        ></c-button-secondary>
      </router-link>
      <c-button-secondary @click="isDeleteCategoryDialogShown = true" :text="$t('delete')"></c-button-secondary>
    </div>
    <c-dialog :title-text="$t('deleteCategory')"
              :subtitle-text="$t('doYouReallyWantToDelete', {name: $t(category.category.toLowerCase())})"
              v-model="isDeleteCategoryDialogShown" @confirm="handleConfirmDeleteCategory()"></c-dialog>
  </div>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary";
import CDialog from "@/components/common/CDialog";

export default {
  name: "CategoryListItem",
  components: {
    CButtonSecondary,
    CDialog
  },
  props: {
    category: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      isDeleteCategoryDialogShown: false
    };
  },
  methods: {
    handleConfirmDeleteCategory() {
      this.$store.dispatch("administratorManagementToolModule/deleteCategory", this.category.id)
        .then(() => {
          this.isDeleteCategoryDialogShown = false;
          this.$store.dispatch("administratorManagementToolModule/fetchCategories", 1);
        })
        .catch(() =>
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$t("somethingWentWrong"),
            type: "error"
          }));
    }
  }
};
</script>

<style scoped>

</style>
