// bachelor-front-react-version-main/src/components/administrator-management-tool/CreateCategoryRequestListItem.tsx
import {
  CategoryApplication,
  CategoryApplicationResponse,
  HandleCategoryApplicationRequest,
} from "../../generated-sources/openapi";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { useTranslation } from "react-i18next";
import { fetchCreateCategoryRequests, handleCreateCategoryRequest } from "../../store/administratorManagementToolSlice";
import { showSnackbar } from "../../store/eventSlice";
import CButtonSecondary from "../common/CButtonSecondary";
import CDialog from "../common/CDialog";

interface Props {
  category: CategoryApplication;
}

function CreateCategoryRequestListItem(props: Props) {
  const dispatch = useDispatch();
  const { t } = useTranslation();

  const { category } = props;

  function handleAcceptCreateCategoryRequest() {
    let handleCategoryApplicationRequest: HandleCategoryApplicationRequest = {
      categoryId: category.id,
      categoryState: CategoryApplicationResponse.Approve,
    };

    // @ts-ignore
    dispatch(handleCreateCategoryRequest(handleCategoryApplicationRequest))
      // @ts-ignore
      .then(() => dispatch(fetchCreateCategoryRequests(1)))
      .catch(() =>
        dispatch(
          showSnackbar({
            message: t("failedToApproveTheRequest"),
            type: "error",
          })
        )
      );
  }

  function handleConfirmRejectCreateCategoryRequest() {
    let handleCategoryApplicationRequest: HandleCategoryApplicationRequest = {
      categoryId: category.id,
      categoryState: CategoryApplicationResponse.Deny,
    };

    // @ts-ignore
    dispatch(handleCreateCategoryRequest(handleCategoryApplicationRequest))
      .then(() => {
        setIsRejectCreateCategoryRequestDialogShown(false);
        // @ts-ignore
        dispatch(fetchCreateCategoryRequests(1));
      })
      .catch(() =>
        dispatch(
          showSnackbar({
            message: t("failedToRejectTheRequest"),
            type: "error",
          })
        )
      );
  }

  const [isRejectCreateCategoryRequestDialogShown, setIsRejectCreateCategoryRequestDialogShown] = useState(false);

  return (
    <div className="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
      <span className="c-text-14 truncate">{category.category}</span>
      <div className="flex items-center gap-x-3 flex-wrap">
        <CButtonSecondary text={t("accept")} onClick={handleAcceptCreateCategoryRequest} />
        <CButtonSecondary text={t("reject")} onClick={() => setIsRejectCreateCategoryRequestDialogShown(true)} />
      </div>
      <CDialog
        subtitleText={t("doYouReallyWantToReject", { name: category.category }) || ""}
        isShown={isRejectCreateCategoryRequestDialogShown}
        onUpdate={setIsRejectCreateCategoryRequestDialogShown}
        titleText={t("rejectNewCategoryRequest") || ""}
        onConfirm={handleConfirmRejectCreateCategoryRequest}></CDialog>
    </div>
  );
}

export default CreateCategoryRequestListItem;

// bachelor-front-vue-version-main/src/components/administrator_management_tool_view/CreateCategoryRequestListItem.vue
<template>
  <div class="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
    <span class="c-text-14 truncate">{{ category.category }}</span>
    <div class="flex items-center gap-x-3 flex-wrap">
      <c-button-secondary @click="handleAcceptCreateCategoryRequest()" :text="$t('accept')"></c-button-secondary>
      <c-button-secondary @click="isRejectCreateCategoryRequestDialogShown = true"
                          :text="$t('reject')"></c-button-secondary>
    </div>
    <c-dialog :title-text="$t('rejectNewCategoryRequest')"
              :subtitle-text="$t('doYouReallyWantToReject', {name: category.category})"
              v-model="isRejectCreateCategoryRequestDialogShown"
              @confirm="handleConfirmRejectCreateCategoryRequest()"></c-dialog>
  </div>
</template>

<script lang="ts">
import CButtonSecondary from "@/components/common/CButtonSecondary.vue";
import CDialog from "@/components/common/CDialog.vue";
import Vue from "vue";
import { CategoryApplicationResponse, HandleCategoryApplicationRequest } from "@/generated-sources/openapi";

export default Vue.extend({
  name: "CreateCategoryRequestListItem",
  components: {
    CButtonSecondary,
    CDialog
  },
  props: {
    category: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      isRejectCreateCategoryRequestDialogShown: false
    };
  },
  methods: {
    handleAcceptCreateCategoryRequest() {
      let handleCategoryApplicationRequest: HandleCategoryApplicationRequest = {
        categoryId: this.category.id,
        categoryState: CategoryApplicationResponse.Approve
      };
      this.$store.dispatch("administratorManagementToolModule/handleCreateCategoryRequest", handleCategoryApplicationRequest)
        .then(() => this.$store.dispatch("administratorManagementToolModule/fetchCreateCategoryRequests", 1))
        .catch(() => this.$store.dispatch("eventModule/showSnackbar", {
          message: this.$t("failedToApproveTheRequest"),
          type: "error"
        }));
    },
    handleConfirmRejectCreateCategoryRequest() {
      let handleCategoryApplicationRequest: HandleCategoryApplicationRequest = {
        categoryId: this.category.id,
        categoryState: CategoryApplicationResponse.Deny
      };
      this.$store.dispatch("administratorManagementToolModule/handleCreateCategoryRequest", handleCategoryApplicationRequest)
        .then(() => {
          this.isRejectCreateCategoryRequestDialogShown = false;
          this.$store.dispatch("administratorManagementToolModule/fetchCreateCategoryRequests", 1);
        })
        .catch(() => this.$store.dispatch("eventModule/showSnackbar", {
          message: this.$t("failedToRejectTheRequest"),
          type: "error"
        }));
    }
  }
});
</script>

<style scoped>

</style>
