// bachelor-front-react-version-main/src/components/common/CPathRepresentation.tsx
import { Link } from "react-router-dom";
import { Fragment } from "react";
import CButtonSecondary from "./CButtonSecondary";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

interface Props {
  directories: { name: string; route?: string }[];
  className?: string;
}

function CPathRepresentation(props: Props) {
  const { directories, className = "" } = props;

  return (
    <div className={className + " flex flex-row items-center"}>
      {directories.map((directory, index) => {
        return (
          <div key={index} className="flex flex-row items-center">
            {index !== directories.length - 1 ? (
              <Fragment>
                <Link to={directory.route || ""}>
                  <CButtonSecondary className="text-left" text={directory.name}></CButtonSecondary>
                </Link>
                {index !== directories.length - 2 ||
                  (directories[directories.length - 1].name && (
                    <FontAwesomeIcon className="mx-2" size="2xs" icon={["fas", "chevron-right"]}></FontAwesomeIcon>
                  ))}
              </Fragment>
            ) : (
              <span className="c-text-12 text-left">{directory.name}</span>
            )}
          </div>
        );
      })}
    </div>
  );
}

export default CPathRepresentation;

// bachelor-front-vue-version-main/src/components/common/CPathRepresentation.vue
<template>
  <div class="flex flex-row items-center">
    <div
      v-for="(directory, index) in directories"
      :key="index"
      class="flex flex-row items-center"
    >
      <template v-if="index !== directories.length - 1">
        <router-link :to="directory.route">
          <c-button-secondary class="text-left" :text="directory.name"></c-button-secondary>
        </router-link>
        <font-awesome-icon
          v-if="index !== directories.length-2 ||directories[directories.length - 1].name"
          class="mx-2"
          size="2xs"
          data-test="chevron"
          icon="fa-solid fa-chevron-right"
        ></font-awesome-icon>
      </template>
      <span v-else class="c-text-12 text-left">{{ directory.name }}</span>
    </div>
  </div>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary";

export default {
  name: "CPathRepresentation",
  props: {
    directories: {
      type: Array,
      required: true
    }
  },
  components: {
    CButtonSecondary
  }
};
</script>

<style scoped></style>
