// bachelor-front-react-version-main/src/components/common/CRatingEdit.tsx
import { useState } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import classNames from "classnames";
import "../../assets/styles/CRatingEdit.css";

interface Props {
  value?: number;
  onUpdate?: (newValue: number) => void;
  className?: string;
}

function CRatingEdit(props: Props) {
  const { value = 0, onUpdate, className = "" } = props;
  const [hoveredValue, setHoveredValue] = useState(-1);

  function handleChangeValue(newValue: number) {
    onUpdate && onUpdate(newValue);
  }

  return (
    <div className={className + " flex flex-col cursor-pointer"}>
      <div className="flex flex-row items-center justify-between">
        <FontAwesomeIcon
          icon={["fas", "star"]}
          className={classNames({
            "text-spun-pearl": value < 1,
            "text-cinder": value >= 1,
            "text-dark-blue": hoveredValue >= 1,
          })}
          onClick={() => handleChangeValue(1)}
          onMouseOver={() => setHoveredValue(1)}
          onMouseLeave={() => setHoveredValue(-1)}></FontAwesomeIcon>
        <FontAwesomeIcon
          icon={["fas", "star"]}
          className={classNames({
            "text-spun-pearl": value < 2,
            "text-cinder": value >= 2,
            "text-dark-blue": hoveredValue >= 2,
          })}
          onClick={() => handleChangeValue(2)}
          onMouseOver={() => setHoveredValue(2)}
          onMouseLeave={() => setHoveredValue(-1)}></FontAwesomeIcon>
        <FontAwesomeIcon
          icon={["fas", "star"]}
          className={classNames({
            "text-spun-pearl": value < 3,
            "text-cinder": value >= 3,
            "text-dark-blue": hoveredValue >= 3,
          })}
          onClick={() => handleChangeValue(3)}
          onMouseOver={() => setHoveredValue(3)}
          onMouseLeave={() => setHoveredValue(-1)}></FontAwesomeIcon>
        <FontAwesomeIcon
          icon={["fas", "star"]}
          className={classNames({
            "text-spun-pearl": value < 4,
            "text-cinder": value >= 4,
            "text-dark-blue": hoveredValue >= 4,
          })}
          onClick={() => handleChangeValue(4)}
          onMouseOver={() => setHoveredValue(4)}
          onMouseLeave={() => setHoveredValue(-1)}></FontAwesomeIcon>
        <FontAwesomeIcon
          icon={["fas", "star"]}
          className={classNames({
            "text-spun-pearl": value < 5,
            "text-cinder": value === 5,
            "text-dark-blue": hoveredValue >= 5,
          })}
          onClick={() => handleChangeValue(5)}
          onMouseOver={() => setHoveredValue(5)}
          onMouseLeave={() => setHoveredValue(-1)}></FontAwesomeIcon>
      </div>
    </div>
  );
}

export default CRatingEdit;

// bachelor-front-vue-version-main/src/components/common/CRatingEdit.vue
<template>
  <div class="flex flex-col cursor-pointer">
    <div class="flex flex-row items-center justify-between">
      <font-awesome-icon
        :class="{
          'text-spun-pearl': value < 1,
          'text-cinder': value >= 1,
          'text-dark-blue': hoveredValue >= 1,
        }"
        class="text-spun-pearl"
        icon="fa-solid fa-star"
        @mouseover="hoveredValue = 1"
        @click="handleChangeValue(1)"
        @mouseleave="hoveredValue = -1"
      />
      <font-awesome-icon
        :class="{
          'text-spun-pearl': value < 2,
          'text-cinder': value >= 2,
          'text-dark-blue': hoveredValue >= 2,
        }"
        class="text-spun-pearl"
        icon="fa-solid fa-star"
        @mouseover="hoveredValue = 2"
        @click="handleChangeValue(2)"
        @mouseleave="hoveredValue = -1"
      />
      <font-awesome-icon
        :class="{
          'text-spun-pearl': value < 3,
          'text-cinder': value >= 3,
          'text-dark-blue': hoveredValue >= 3,
        }"
        class="text-spun-pearl"
        icon="fa-solid fa-star"
        @click="handleChangeValue(3)"
        @mouseover="hoveredValue = 3"
        @mouseleave="hoveredValue = -1"
      >
      </font-awesome-icon>
      <font-awesome-icon
        :class="{
          'text-spun-pearl': value < 4,
          'text-cinder': value >= 4,
          'text-dark-blue': hoveredValue >= 4,
        }"
        class="text-spun-pearl"
        @mouseover="hoveredValue = 4"
        @mouseleave="hoveredValue = -1"
        @click="handleChangeValue(4)"
        icon="fa-solid fa-star"></font-awesome-icon>
      <font-awesome-icon
        :class="{
          'text-spun-pearl': value < 5,
          'text-cinder': value === 5,
          'text-dark-blue': hoveredValue >= 5,
        }"
        class="text-spun-pearl"
        @mouseover="hoveredValue = 5"
        @mouseleave="hoveredValue = -1"
        @click="handleChangeValue(5)"
        icon="fa-solid fa-star">
      </font-awesome-icon>
    </div>
  </div>
</template>

<script>

export default {
  name: "CRatingEdit",
  data() {
    return {
      hoveredValue: -1
    };
  },
  props: {
    value: {
      type: Number,
      default: 0
    }
  },
  model: {
    prop: "value",
    event: "update"
  },
  methods: {
    handleChangeValue(value) {
      this.$emit("update", value);
    }
  }
};
</script>

<style scoped>
.text-dark-blue {
  color: var(--dark-blue) !important;
}
</style>
