// bachelor-front-react-version-main/src/components/common/CTabsNavigation.tsx
import CButtonSecondary from "./CButtonSecondary";

interface Props {
  tabs: { selected: boolean; name: string }[];
  onTabSelected: (tab: { selected: boolean; name: string }) => void;
  className?: string;
}

function CTabsNavigation(props: Props) {
  const { tabs, onTabSelected, className = "" } = props;

  return (
    <div className={className + " flex flex-row gap-3 flex-wrap"}>
      {tabs.map((tab, index) => (
        <div key={index}>
          {tab.selected ? (
            <span className="block c-text-12 text-mid-gray cursor-default">{tab.name}</span>
          ) : (
            <CButtonSecondary type="button" onClick={() => onTabSelected(tab)} text={tab.name}></CButtonSecondary>
          )}
        </div>
      ))}
    </div>
  );
}

export default CTabsNavigation;

// bachelor-front-vue-version-main/src/components/common/CTabsNavigation.vue
<template>
  <div class="flex flex-row gap-3 flex-wrap">
    <div v-for="(tab, index) in tabs" :key="index">
      <span v-if="tab.selected" class="block c-text-12 text-mid-gray cursor-default">{{ tab.name }}</span>
      <c-button-secondary @click="$emit('tabSelected', tab)" v-else type="button" :text="tab.name"></c-button-secondary>
    </div>
  </div>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary.vue";

export default {
  name: "CTabsNavigation",
  components: {
    CButtonSecondary
  },
  props: {
    tabs: {
      type: Array,
      required: true
    }
  }
};
</script>

<style scoped>

</style>
