// bachelor-front-vue-version-main/src/components/navigation_bar/NavigationBar.vue
<template>
  <div
    class="h-24 flex flex-shrink-0 border-b border-mid-gray border-solid justify-center"
  >
    <div class="container flex flex-shrink-0 items-center">
      <router-link to="/" v-if="isLimitedNavigationBar" class="mr-8">
        <font-awesome-icon
          size="xl"
          class="text-dark-blue"
          icon="fa-solid fa-arrow-left"
          :title="$t('goBack')"
        />
      </router-link>
      <font-awesome-icon
        data-cy="nav-side-bar-button"
        @click="isLeftSideBarShown = true"
        v-else
        size="xl"
        class="text-dark-blue mr-8 cursor-pointer"
        icon="fa-solid fa-bars"
        :title="$t('menu')"
      />
      <router-link to="/" :title="$t('frontPage')" data-cy="base-button">
        <img src="@/assets/images/logo.png" class="w-20" alt="">
<!--        <span-->
<!--          class="text-2xl font-bold text-dark-blue underline hover:no-underline"-->
<!--          >abobus</span-->
<!--        >-->
      </router-link
      >
      <div
        v-if="!isLimitedNavigationBar"
        class="hidden flex-row grow items-center sm:flex ml-8"
      >
        <div class="flex grow"></div>
        <div class="flex grow flex-col mr-7" style="max-width: calc(96px * 4)">
          <navigation-bar-search></navigation-bar-search>
        </div>
        <router-link to="/cart" class="mr-8" :title="$t('cart')" data-cy="cart-button">
          <font-awesome-icon
            :class="[
              isCurrentRoute('cart') ? 'text-dark-blue' : 'text-mid-gray',
            ]"
            class="hover:text-dark-blue"
            icon="fa-solid fa-cart-shopping"
          />
        </router-link>
        <router-link to="/favorites" class="mr-8" :title="$t('favorites')" data-cy="favorites-button">
          <font-awesome-icon
            :class="[
              isCurrentRoute('favorites') ? 'text-dark-blue' : 'text-mid-gray',
            ]"
            class="hover:text-dark-blue"
            icon="fa-solid fa-heart"
          />
        </router-link>
        <router-link
          data-cy="business-management-tool-button"
          v-if="isBusinessManagementToolShown()"
          to="/business-management-tool"
          :title="$t('businessManagementTool')"
        >
          <font-awesome-icon
            :class="[
              isCurrentRoute('businessManagementTool')
                ? 'text-dark-blue'
                : 'text-mid-gray',
            ]"
            class="hover:text-dark-blue mr-8"
            icon="fa-solid fa-briefcase"
          />
        </router-link>
        <router-link
          data-cy="administrator-management-tool-button"
          v-if="isAdministratorManagementToolShown()"
          to="/administrator-management-tool"
          :title="$t('administratorManagementTool')"
        >
          <font-awesome-icon
            :class="[
              isCurrentRoute('administratorManagementTool')
                ? 'text-dark-blue'
                : 'text-mid-gray',
            ]"
            class="hover:text-dark-blue mr-8"
            icon="fa-solid fa-solar-panel"
          />
        </router-link>
        <router-link to="/account" :title="$t('account')" data-cy="account-button">
          <font-awesome-icon
            :class="[
              isCurrentRoute('account') ? 'text-dark-blue' : 'text-mid-gray',
            ]"
            class="hover:text-dark-blue"
            icon="fa-solid fa-user"
          />
        </router-link>
      </div>
    </div>
    <navigation-bar-left-side-bar
      @closeClicked="isLeftSideBarShown = false"
      v-if="isLeftSideBarShown"
    ></navigation-bar-left-side-bar>
  </div>
</template>

<script>
import NavigationBarSearch from "@/components/navigation_bar/NavigationBarSearch";
import NavigationBarLeftSideBar from "@/components/navigation_bar/NavigationBarLeftSideBar";
import Vue from "vue";

export default {
  name: "NavigationBar",
  components: {
    NavigationBarSearch,
    NavigationBarLeftSideBar,
  },
  computed: {
    isLimitedNavigationBar() {
      return this.$route.meta.limitedNavigationBar;
    },
  },
  data() {
    return {
      isLeftSideBarShown: false,
      isRightSideBarShown: false,
    };
  },
  methods: {
    isCurrentRoute(routeName) {
      return this.$route.matched[0]?.name === routeName;
    },
    isBusinessManagementToolShown() {
      return Vue.$keycloak?.realmAccess?.roles?.includes("BUSINESS_OWNER");
    },
    isAdministratorManagementToolShown() {
      return Vue.$keycloak?.realmAccess?.roles?.includes("ADMIN");
    },
  },
};
</script>

// bachelor-front-react-version-main/src/components/navigation-bar/NavigationBar.tsx
import { Link } from "react-router-dom";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useTranslation } from "react-i18next";
import { useState } from "react";
import NavigationBarSearch from "./NavigationBarSearch";
import classNames from "classnames";
import NavigationBarLeftSideBar from "./NavigationBarLeftSideBar";
import keycloak from "../../authentication/keycloak";
import { useLocation } from "react-router-dom";
import { routePathsRequiringLimitedNavigationBar } from "../../App";

function NavigationBar() {
  const { t } = useTranslation();
  const location = useLocation();

  const [isLeftSideBarShown, setIsLeftSideBarShown] = useState(false);

  const isLimitedNavigationBar = routePathsRequiringLimitedNavigationBar
    .map((routepath) => isCurrentRoute(routepath))
    .includes(true);
  const isBusinessManagementToolShown = keycloak?.realmAccess?.roles?.includes("BUSINESS_OWNER") || false;
  const isAdministratorManagementToolShown = keycloak?.realmAccess?.roles?.includes("ADMIN") || false;

  function isCurrentRoute(pathname: string): boolean {
    return location.pathname.includes(pathname);
  }

  function handleShowLeftSideBarClick() {
    setIsLeftSideBarShown(true);
  }

  function handleHideLeftSideBarClick() {
    setIsLeftSideBarShown(false);
  }

  return (
    <nav className="h-24 flex flex-shrink-0 border-b border-mid-gray border-solid justify-center">
      <div className="container flex flex-shrink-0 items-center">
        {isLimitedNavigationBar ? (
          <Link to="/" className="mr-8">
            <FontAwesomeIcon
              title={t("goBack") + ""}
              size="xl"
              className="text-dark-blue"
              icon={["fas", "arrow-left"]}></FontAwesomeIcon>
          </Link>
        ) : (
          <FontAwesomeIcon
            title={t("menu") + ""}
            className="text-dark-blue mr-8 cursor-pointer"
            size="xl"
            onClick={handleShowLeftSideBarClick}
            icon={["fas", "bars"]}></FontAwesomeIcon>
        )}
        <Link to="/" title={t("frontPage") + ""}>
          <img src={require("../../assets/images/logo.png")} className="w-20" alt="" />
        </Link>
        {!isLimitedNavigationBar && (
          <div className="hidden flex-row grow items-center sm:flex ml-8">
            <div className="flex grow"></div>
            <div className="flex grow flex-col mr-7" style={{ maxWidth: "calc(96px * 4)" }}>
              <NavigationBarSearch></NavigationBarSearch>
            </div>
            <Link to="/cart" className="mr-8" title={t("cart") + ""}>
              <FontAwesomeIcon
                icon={["fas", "cart-shopping"]}
                className={classNames({
                  "hover:text-dark-blue": true,
                  "text-dark-blue": isCurrentRoute("/cart"),
                  "text-mid-gray": !isCurrentRoute("/cart"),
                })}></FontAwesomeIcon>
            </Link>
            <Link to="/favorites" className="mr-8" title={t("favorites") + ""}>
              <FontAwesomeIcon
                icon={["fas", "heart"]}
                className={classNames({
                  "hover:text-dark-blue": true,
                  "text-dark-blue": isCurrentRoute("/favorites"),
                  "text-mid-gray": !isCurrentRoute("/favorites"),
                })}></FontAwesomeIcon>
            </Link>
            {isBusinessManagementToolShown && (
              <Link to="/business-management-tool" className="mr-8" title={t("businessManagementTool") + ""}>
                <FontAwesomeIcon
                  icon={["fas", "briefcase"]}
                  className={classNames({
                    "hover:text-dark-blue": true,
                    "text-dark-blue": isCurrentRoute("/businessManagementTool"),
                    "text-mid-gray": !isCurrentRoute("/businessManagementTool"),
                  })}></FontAwesomeIcon>
              </Link>
            )}
            {isAdministratorManagementToolShown && (
              <Link to="/administrator-management-tool" className="mr-8" title={t("administratorManagementTool") + ""}>
                <FontAwesomeIcon
                  icon={["fas", "solar-panel"]}
                  className={classNames({
                    "hover:text-dark-blue": true,
                    "text-dark-blue": isCurrentRoute("/administratorManagementTool"),
                    "text-mid-gray": !isCurrentRoute("/administratorManagementTool"),
                  })}></FontAwesomeIcon>
              </Link>
            )}
            <Link to="/account" className="mr-8" title={t("account") + ""}>
              <FontAwesomeIcon
                icon={["fas", "user"]}
                className={classNames({
                  "hover:text-dark-blue": true,
                  "text-dark-blue": isCurrentRoute("/account"),
                  "text-mid-gray": !isCurrentRoute("/account"),
                })}></FontAwesomeIcon>
            </Link>
          </div>
        )}
      </div>
      {isLeftSideBarShown && (
        <NavigationBarLeftSideBar
          onCloseClick={handleHideLeftSideBarClick}
          isAdministratorManagementToolShown={isAdministratorManagementToolShown}
          isBusinessManagementToolShown={isBusinessManagementToolShown}
          isCurrentRoute={isCurrentRoute}></NavigationBarLeftSideBar>
      )}
    </nav>
  );
}

export default NavigationBar;
