// bachelor-front-react-version-main/src/components/product/ProductViewSideBar.tsx
import { useDispatch, useSelector } from "react-redux";
import { useTranslation } from "react-i18next";
import { RootState } from "../../store";
import { stringFormatterHelper } from "../../utils/stringFormatterHelper";
import { useEffect, useRef, useState } from "react";
import keycloak from "../../authentication/keycloak";
import { fetchCurrentUserData } from "../../store/userSlice";
import useEscapeKeyHandler from "../../hooks/useEscapeKeyHandler";
import { hideLoadingOverlay, showLoadingOverlay, showSnackbar } from "../../store/eventSlice";
import { addComment, addCommentReply, fetchComments, updateRating } from "../../store/productSlice";
import { eventBus } from "../../eventBus";
import { CreateNewCommentReplyRequest, CreateNewCommentRequest } from "../../generated-sources/openapi";
import useClickOutside from "../../hooks/useClickOutside";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import CRating from "../common/CRating";
import CButtonPrimary from "../common/CButtonPrimary";
import CRatingEdit from "../common/CRatingEdit";
import CButtonSecondary from "../common/CButtonSecondary";
import CComment from "../common/CComment";
import classNames from "classnames";
import CTextarea from "../common/CTextarea";
import { validatorHelper } from "../../utils/validatorHelper";

interface Props {
  onCloseClicked: () => void;
  productId: string;
}

function ProductViewSideBar(props: Props) {
  const { t } = useTranslation();
  const dispatch = useDispatch();

  const { onCloseClicked, productId } = props;

  const { product, comments, isCommentsLoading } = useSelector((state: RootState) => state.product);
  const { ratedProducts } = useSelector((state: RootState) => state.user);

  const [isNewCommentShown, setIsNewCommentShown] = useState(false);
  const [isNewCommentLoading, setIsNewCommentLoading] = useState(false);
  const [newComment, setNewComment] = useState("");
  const [isReplyLoading, setIsReplyLoading] = useState(false);
  const [isReplyEnabled, setIsReplyEnabled] = useState(keycloak?.authenticated);
  const [isEditRating, setIsEditRating] = useState(false);
  const [isRateProductButtonEnabled, setIsRateProductButtonEnabled] = useState(false);
  const [ratingSetByCurrentUser, setRatingSetByCurrentUser] = useState(0);

  const cTextareaNewCommentRef = useRef(null);
  const sideBarRef = useRef(null);

  useEscapeKeyHandler(handleClickOutside);

  useClickOutside(sideBarRef, handleClickOutside);

  useEffect(() => {
    if (keycloak.authenticated) {
      // @ts-ignore
      dispatch(fetchCurrentUserData());
    }

    if (!comments?.some((c) => c.productId === product?.id)) {
      dispatch(showLoadingOverlay({ isInstant: false }));
      // @ts-ignore
      dispatch(fetchComments(true)).finally(() => dispatch(hideLoadingOverlay()));
    }
  }, []);

  useEffect(() => {
    eventBus.on("close-reply-section", handleCloseReplySection);
    return () => eventBus.off("close-reply-section", handleCloseReplySection);
  }, []);

  useEffect(() => {
    verifyAndSetRatingSetByCurrentUser();
  }, [ratedProducts]);

  const formattedRating = stringFormatterHelper.replaceDotsWithCommas((product?.rating?.overallRating || 0).toString());

  function handleUpdateRating() {
    // @ts-ignore
    dispatch(updateRating(ratingSetByCurrentUser)).then(() => setIsEditRating(false));
  }

  function verifyAndSetRatingSetByCurrentUser() {
    let currentUserRatingForCurrentProduct = ratedProducts.find((rating) => rating.ratedProductId === productId);
    setRatingSetByCurrentUser(currentUserRatingForCurrentProduct?.rating || 0);
  }

  function scrollToEnd() {
    setTimeout(() => {
      document.getElementById("target-new-comment-section")?.scrollIntoView({ behavior: "smooth", inline: "end" });
    }, 0);
  }

  function handleShowPostNewComment() {
    if (keycloak.authenticated) {
      eventBus.emit("close-reply-section");
      setIsNewCommentShown(true);
      scrollToEnd();
    } else {
      keycloak.login({
        // eslint-disable-next-line no-restricted-globals
        redirectUri: process.env.REACT_APP_URL + location.pathname,
      });
    }
  }

  function handleRateProduct() {
    if (keycloak.authenticated) {
      setIsEditRating(true);
    } else {
      keycloak.login({
        // eslint-disable-next-line no-restricted-globals
        redirectUri: process.env.REACT_APP_URL + location.pathname,
      });
    }
  }

  function postNewComment() {
    // @ts-ignore
    let isCommentValid = cTextareaNewCommentRef?.current?.validateInput();
    if (isCommentValid) {
      let createNewCommentRequest: Required<CreateNewCommentRequest> = {
        productId: product?.id || "",
        text: newComment,
      };
      setIsNewCommentLoading(true);
      // @ts-ignore
      dispatch(addComment(createNewCommentRequest))
        .then(() => {
          setIsNewCommentShown(false);
          setNewComment("");
          // @ts-ignore
          dispatch(fetchComments()).then(() => scrollToEnd());
        })
        .catch(() =>
          dispatch(
            showSnackbar({
              message: t("failedToPostTheComment"),
              type: "error",
            })
          )
        )
        .finally(() => setIsNewCommentLoading(false));
    }
  }

  function postNewCommentReply(partOfReply: Pick<CreateNewCommentReplyRequest, "targetCommentId" | "text">) {
    let createNewCommentReplyRequest: CreateNewCommentReplyRequest = {
      ...partOfReply,
      productId: product?.id || "",
    };
    setIsReplyLoading(true);
    // @ts-ignore
    dispatch(addCommentReply(createNewCommentReplyRequest))
      // @ts-ignore
      .then(() => dispatch(fetchComments()))
      .catch(() =>
        dispatch(
          showSnackbar({
            message: t("failedToPostTheComment"),
            type: "error",
          })
        )
      )
      .finally(() => setIsReplyLoading(false));
  }

  function handleClickOutside() {
    onCloseClicked();
  }

  function handleCloseReplySection() {
    setIsNewCommentShown(false);
  }

  function handleNewRatingSelected(newRating: number) {
    setRatingSetByCurrentUser(newRating);
  }

  function handleCloseEditRating() {
    setIsEditRating(false);
  }

  return (
    <div className="w-screen h-screen fixed bg-background z-50 top-0 left-0 flex flex-row justify-end">
      <div
        className={"sm:w-[480px] w-full flex flex-col h-full bg-white sm:border-l border-mid-gray border-solid"}
        ref={sideBarRef}>
        <nav
          className={
            "sm:pr-20 px-[16px] h-24 flex flex-row items-center justify-end border-b border-mid-gray border-solid shrink-0"
          }>
          <FontAwesomeIcon
            className={"text-dark-blue cursor-pointer"}
            size="xl"
            onClick={onCloseClicked}
            title={t("goBack") || ""}
            icon={["fas", "close"]}></FontAwesomeIcon>
        </nav>
        <main className="sm:p-10 px-[16px] py-[40px] overflow-y-auto flex flex-col grow">
          <h3>{t("reviews")}</h3>
          {!isEditRating ? (
            <div className={"flex flex-col"}>
              <h1 className="mt-10">{formattedRating}</h1>
              <CRating
                isTotalRatingShown={true}
                isNumericRatingShown={false}
                value={product?.rating?.overallRating || 0}
                totalRatings={product?.rating?.totalRatings || 0}></CRating>
              <CButtonPrimary
                className={"mt-5 self-start"}
                text={t("rateProduct")}
                onClick={handleRateProduct}></CButtonPrimary>
            </div>
          ) : (
            <div className={"flex flex-col"}>
              <p className="font-bold mt-7">{t("rateProduct")}</p>
              <CRatingEdit
                className={"mt-10 px-6"}
                value={ratingSetByCurrentUser}
                onUpdate={handleNewRatingSelected}></CRatingEdit>
              <div className="flex flex-row justify-end mt-10 gap-4">
                <CButtonSecondary text={t("cancel")} onClick={handleCloseEditRating}></CButtonSecondary>
                <CButtonPrimary
                  className={"self-end"}
                  iconEnd={["fas", "paper-plane"]}
                  text={t("rate")}
                  onClick={handleUpdateRating}></CButtonPrimary>
              </div>
            </div>
          )}
          <p className="font-bold mt-10">{t("comments")}</p>
          <div className="flex flex-col grow">
            {!comments?.length && !isCommentsLoading && (
              <div className={"flex flex-col grow items-center justify-center"}>
                <h4 className="text-spun-pearl">{t("noComments")}</h4>
              </div>
            )}
            <div className="flex flex-col mb-3">
              {comments?.map((comment) => (
                <CComment
                  isCommentLoading={isReplyLoading}
                  onPostNewComment={postNewCommentReply}
                  isReplyEnabled={isReplyEnabled}
                  key={comment.commentNodeId}
                  messageObject={comment}></CComment>
              ))}
            </div>
            <div
              className={classNames({
                grow: comments?.length,
                "flex flex-col justify-end": true,
              })}>
              <div
                className={classNames({
                  hidden: !isNewCommentShown,
                  "flex flex-col mt-10": true,
                })}>
                <CTextarea
                  ref={cTextareaNewCommentRef}
                  isDisabled={isNewCommentLoading}
                  grow={true}
                  size="small"
                  value={newComment}
                  onUpdate={setNewComment}
                  rows={2}
                  validateOnBlur={false}
                  validatorFunctions={[validatorHelper.validateRequired]}
                  placeholder={t("typeANewComment") || ""}></CTextarea>
                <div className="flex flex-row mt-3 gap-4 justify-end">
                  <CButtonSecondary text={t("cancel")} onClick={handleCloseReplySection}></CButtonSecondary>
                  <CButtonPrimary
                    isDisabled={isNewCommentLoading}
                    iconEnd={["fas", "paper-plane"]}
                    className={"self-end"}
                    onClick={postNewComment}
                    text={t("post")}></CButtonPrimary>
                </div>
              </div>
              <div id="target-new-comment-section"></div>
            </div>
            {!isNewCommentShown && (
              <CButtonPrimary
                className={"self-end sticky bottom-0 bg-white"}
                onClick={handleShowPostNewComment}
                iconEnd={["fas", "pen"]}
                text={t("writeAComment")}></CButtonPrimary>
            )}
          </div>
        </main>
      </div>
    </div>
  );
}

export default ProductViewSideBar;

// bachelor-front-vue-version-main/src/components/product_view/ProductViewSideBar.vue
<template>
  <div class="w-screen h-screen fixed bg-background z-50 top-0 left-0 flex flex-row justify-end">
    <div
      v-click-outside="handleClickOutside"
      class="sm:w-[480px] w-full flex flex-col h-full bg-white sm:border-l border-mid-gray border-solid"
    >
      <nav
        class="sm:pr-20 px-[16px] h-24 flex flex-row items-center justify-end border-b border-mid-gray border-solid shrink-0">
        <font-awesome-icon
          :title="$t('goBack')"
          @click="$emit('closeClicked')"
          size="xl"
          class="text-dark-blue cursor-pointer"
          icon="fa-solid fa-close"
        />
      </nav>
      <main class="sm:p-10 px-[16px] py-[40px] overflow-y-auto flex flex-col grow">
        <h3>{{ $t("reviews") }}</h3>
        <div v-if="!isEditRating" class="flex flex-col">
          <h1 class="mt-10">{{ formattedRating }}</h1>
          <c-rating is-total-rating-shown
                    :is-numeric-rating-shown="false"
                    :value="$store.state.productModule.product.rating.overallRating || 0"
                    :total-ratings="$store.state.productModule.product.rating.totalRatings || 0"></c-rating>
          <c-button-primary
            class="mt-5 self-start" is-total-rating-shown
            :text="$t('rateProduct')"
            @click="handleRateProduct()"></c-button-primary>
        </div>
        <div v-else class="flex flex-col">
          <p class="font-bold mt-7">{{ $t("rateProduct") }}</p>
          <c-rating-edit v-model="ratingSetByCurrentUser" @change="handleUpdateRating"
                         class="mt-10 px-6"></c-rating-edit>
          <div class="flex flex-row justify-end mt-10 gap-4">
            <c-button-secondary @click="isEditRating = false" :text="$t('cancel')"></c-button-secondary>
            <c-button-primary @click="handleUpdateRating()"
                              icon-end="fa-solid fa-paper-plane"
                              class="self-end "
                              :text="$t('rate')"></c-button-primary>
          </div>
        </div>
        <p class="font-bold mt-10">{{ $t("comments") }}</p>
        <div class="flex flex-col grow">
          <div v-if="!$store.state.productModule.comments.length && !$store.state.productModule.isCommentsLoading"
               class="flex flex-col grow items-center justify-center">
            <h4 class="text-spun-pearl">{{ $t("noComments") }}</h4>
          </div>
          <div class="flex flex-col mb-3">
            <c-comment :is-comment-loading="isReplyLoading" @postNewComment="postNewCommentReply"
                       :message-object="comment"
                       :is-reply-enabled="isReplyEnabled"
                       v-for="comment in $store.state.productModule.comments"
                       :key="comment.commentNodeId">
            </c-comment>
          </div>
          <div :class="[$store.state.productModule.comments.length ? 'grow' : '', 'flex flex-col justify-end']">
            <div class="flex flex-col mt-10" v-show="isNewCommentShown">
              <c-textarea :is-disabled="isNewCommentLoading" grow ref="cTextareaNewComment" size="small"
                          v-model="newComment"
                          :rows="2"
                          data-cy="comment-textarea"
                          :validate-on-blur="false" :validator-functions="[validateRequired]"
                          :placeholder="$t('typeANewComment')"></c-textarea>
              <div class="flex flex-row mt-3 gap-4 justify-end">
                <c-button-secondary @click="isNewCommentShown = false" :text="$t('cancel')"></c-button-secondary>
                <c-button-primary :is-disabled="isNewCommentLoading" @click="postNewComment()"
                                  icon-end="fa-solid fa-paper-plane"
                                  class="self-end "
                                  data-cy="post-comment-button"
                                  :text="$t('post')"></c-button-primary>
              </div>
            </div>
            <div id="target-new-comment-section"></div>
          </div>
          <c-button-primary v-if="!isNewCommentShown" @click="handleShowPostNewComment()"
                            class="self-end sticky bottom-0 bg-white"
                            icon-end="fa-solid fa-pen"
                            data-cy="write-a-comment-button"
                            :text="$t('writeAComment')"></c-button-primary>
        </div>
      </main>
    </div>
  </div>
</template>

<script lang="ts">
import { stringFormatter } from "@/util/stringFormatter";
import CRating from "@/components/common/CRating.vue";
import CButtonPrimary from "@/components/common/CButtonPrimary.vue";
import CComment from "@/components/common/CComment.vue";
import validatorMixin from "@/util/validatorMixin";
import CTextarea from "@/components/common/CTextarea.vue";
import Vue from "vue";
import { CreateNewCommentReplyRequest, CreateNewCommentRequest } from "@/generated-sources/openapi";
import CButtonSecondary from "@/components/common/CButtonSecondary.vue";
import CRatingEdit from "@/components/common/CRatingEdit.vue";

// 640
export default Vue.extend({
  name: "ProductViewSideBar",
  components: { CRatingEdit, CButtonSecondary, CComment, CButtonPrimary, CRating, CTextarea },
  mixins: [validatorMixin],
  computed: {
    formattedRating() {
      return stringFormatter.replaceDotsWithCommas(this.$store.state.productModule.product?.rating.overallRating || 0);
    }
  },
  created() {
    this.isReplyEnabled = this.$keycloak.authenticated;

    if (this.$keycloak.authenticated)
      this.$store.dispatch("userModule/fetchCurrentUserData");

    this.verifyAndSetRatingSetByCurrentUser();

    document.addEventListener("keyup", this.handleKeyReleased);
    if (!this.$store.state.productModule.comments.some(c => c.productId === this.$store.state.productModule.product.id)) {
      this.$store.dispatch("eventModule/showLoadingOverlay");
      this.$store.dispatch("productModule/fetchComments", true)
        .finally(() => this.$store.dispatch("eventModule/hideLoadingOverlay"));
    }
  },
  watch: {
    "$store.state.userModule.ratedProducts"() {
      this.verifyAndSetRatingSetByCurrentUser();
    }
  },
  mounted() {
    this.$root.$on("close-reply-section", () => {
      this.isNewCommentShown = false;
    });
  },
  beforeDestroy() {
    this.$root.$off("close-reply-section");
    document.removeEventListener("keyup", this.handleKeyReleased);
  },
  data() {
    return {
      isNewCommentShown: false,
      isNewCommentLoading: false,
      newComment: "",
      isReplyLoading: false,
      isReplyEnabled: false,
      isEditRating: false,
      isRateProductButtonEnabled: false,
      ratingSetByCurrentUser: 0
    };
  },
  methods: {
    handleUpdateRating() {
      this.$store.dispatch("productModule/updateRating", this.ratingSetByCurrentUser)
        .then(() => {
          this.isEditRating = false;
        });
    },
    verifyAndSetRatingSetByCurrentUser() {
      let currentUserRatingForCurrentProduct = this.$store.state.userModule.ratedProducts.find(rating => rating.ratedProductId === this.$route.params.productId);
      this.ratingSetByCurrentUser = currentUserRatingForCurrentProduct?.rating || 0;
    },
    scrollToEnd() {
      setTimeout(() => {
        document.getElementById("target-new-comment-section")?.scrollIntoView({ behavior: "smooth", inline: "end" });
      }, 0);
    },
    handleShowPostNewComment() {
      if (this.$keycloak.authenticated) {
        this.$root.$emit("close-reply-section");
        this.isNewCommentShown = true;
        this.scrollToEnd();
      } else {
        this.$keycloak.login({
          redirectUri: process.env.VUE_APP_URL + this.$route.fullPath
        });
      }
    },
    handleClickOutside() {
      this.$emit("closeClicked");
    },
    handleKeyReleased(e) {
      if (e.key === "Escape") {
        this.handleClickOutside();
      }
    },
    handleRateProduct() {
      if (this.$keycloak.authenticated) {
        this.isEditRating = true;
      } else {
        this.$keycloak.login({
          redirectUri: process.env.VUE_APP_URL + this.$route.fullPath
        });
      }
    },
    postNewComment() {
      let isCommentValid = this.$refs.cTextareaNewComment.validateInput();
      if (isCommentValid) {
        let createNewCommentRequest: Required<CreateNewCommentRequest> = {
          productId: this.$store.state.productModule.product.id,
          text: this.newComment
        };
        this.isNewCommentLoading = true;
        this.$store.dispatch("productModule/addComment", createNewCommentRequest).then(() => {
          this.isNewCommentShown = false;
          this.newComment = "";
          this.$store.dispatch("productModule/fetchComments")
            .then(() => {
              this.scrollToEnd();
            });
        }).catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$t("failedToPostTheComment"),
            type: "error"
          });
        }).finally(() => {
          this.isNewCommentLoading = false;
        });
      }
    },
    postNewCommentReply(partOfReply: Pick<CreateNewCommentReplyRequest, "targetCommentId" | "text">) {
      let createNewCommentReplyRequest: Required<CreateNewCommentReplyRequest> = {
        ...partOfReply,
        productId: this.$store.state.productModule.product.id
      };
      this.isReplyLoading = true;
      this.$store.dispatch("productModule/addCommentReply", createNewCommentReplyRequest).then(() => {
        this.$store.dispatch("productModule/fetchComments");
      }).catch(() => {
        this.$store.dispatch("eventModule/showSnackbar", {
          message: this.$t("failedToPostTheComment"),
          type: "error"
        });
      }).finally(() => {
        this.isReplyLoading = false;
      });
    }
  }
});
</script>

<style scoped>

</style>
