// bachelor-front-react-version-main/src/components/products-list/ProductsListItem.tsx
import { Product } from "../../generated-sources/openapi";
import { useDispatch, useSelector } from "react-redux";
import { useTranslation } from "react-i18next";
import { stringFormatterHelper } from "../../utils/stringFormatterHelper";
import { addProductToCart, removeProductFromCart, updateProductAmountInCart } from "../../store/cartSlice";
import { addProductToFavorites, removeProductFromFavorites } from "../../store/favoritesSlice";
import "../../assets/styles/ProductsListItem.scss";
import { Link } from "react-router-dom";
import CImageWithFallback from "../common/CImageWithFallback";
import CButtonSecondary from "../common/CButtonSecondary";
import { RootState } from "../../store";
import CMenu from "../common/CMenu";
import CButtonPrimary from "../common/CButtonPrimary";

interface Props {
  mode: "cart" | "favorite";
  amount?: number;
  product?: Product;
}

function ProductsListItem(props: Props) {
  const dispatch = useDispatch();
  const { t } = useTranslation();

  const { mode, amount = 0, product } = props;

  const { products } = useSelector((state: RootState) => state.cart);
  const { favorites } = useSelector((state: RootState) => state.favorites);

  function getFormattedPrice() {
    if (mode === "cart") {
      return stringFormatterHelper.getFormattedPrice((product?.price || 0) * amount);
    } else {
      return stringFormatterHelper.getFormattedPrice(product?.price || 0);
    }
  }

  function getQuantityValues() {
    if (mode === "cart") {
      return Array.from({ length: 20 }, (_, i) => i + 1).map((value) => ({
        text: value.toString(),
        selected: value.toString() === amount.toString(),
        function: () => handleQuantityChange(value),
      }));
    }
    return [];
  }

  function handleRemoveItemFromCart() {
    // @ts-ignore
    dispatch(removeProductFromCart(product?.id, true));
  }

  function handleQuantityChange(value: number) {
    // @ts-ignore
    dispatch(updateProductAmountInCart(product?.id, value));
  }

  function handleMoveToFavorites() {
    // @ts-ignore
    dispatch(addProductToFavorites(product?.id));
    // @ts-ignore
    dispatch(removeProductFromCart(product?.id, true));
  }

  function handleMoveItemToCart() {
    // @ts-ignore
    dispatch(addProductToCart(product?.id));
    // @ts-ignore
    dispatch(removeProductFromFavorites(product?.id, true));
  }

  function handleRemoveItemFromFavorites() {
    // @ts-ignore
    dispatch(removeProductFromFavorites(product?.id, true));
  }

  function isProductInCart(id: string) {
    return (products || []).some((p) => p.product?.id === id);
  }

  function isProductInFavorites(id: string) {
    return (favorites || []).some((p) => p.id === id);
  }

  return (
    <div data-css="ProductsListItem" className="flex flex-row gap-6">
      <Link to={"/product/" + product?.id} className={"shrink-0"}>
        <CImageWithFallback
          className={"rounded-lg aspect-square w-[96px] sm:w-[144px] self-start object-cover"}
          src={product?.mainImage?.imageUrl}></CImageWithFallback>
      </Link>
      <div className="flex flex-col grow min-w-0">
        <div className="flex flex-row justify-space-between">
          <Link to={"/product/" + product?.id} className={"block font-bold cursor-default truncate"}>
            <span title={product?.name}>{product?.name}</span>
          </Link>
          <span className="block font-bold shrink-0 ml-2">{getFormattedPrice()}</span>
        </div>
        <Link to={"/product/" + product?.id}>
          <p className={"text-cinder break-words"} title={product?.description}>
            {product?.description}
          </p>
        </Link>
        {mode === "favorite" ? (
          <div className={"mt-7 flex flex-row gap-5"}>
            {!isProductInCart(product?.id || "") && (
              <CButtonSecondary type="button" text={t("moveToCart")} onClick={handleMoveItemToCart}></CButtonSecondary>
            )}
            <CButtonSecondary
              type="button"
              onClick={handleRemoveItemFromFavorites}
              text={t("remove")}></CButtonSecondary>
          </div>
        ) : (
          <div className={"mt-7 flex flex-row gap-5 flex-wrap"}>
            <CMenu isRadio={true} items={getQuantityValues()}>
              <CButtonPrimary type="button" text={amount.toString()} iconEnd={["fas", "chevron-down"]}></CButtonPrimary>
            </CMenu>
            {!isProductInFavorites(product?.id || "") && (
              <CButtonSecondary
                onClick={handleMoveToFavorites}
                type={"button"}
                text={t("moveToFavorites")}></CButtonSecondary>
            )}
            <CButtonSecondary type="button" text={t("remove")} onClick={handleRemoveItemFromCart}></CButtonSecondary>
          </div>
        )}
      </div>
    </div>
  );
}

export default ProductsListItem;

// bachelor-front-vue-version-main/src/components/products_list/ProductsListItem.vue
<template>
  <div class="flex flex-row gap-6">
    <router-link :to="{name: 'product', params: {productId: product.id}}" class="shrink-0">
      <img
        :src="product.mainImage.imageUrl"
        @error="(e) => e.target.src = require('@/assets/images/image_failed_to_load.svg')"
        alt=""
        class="rounded-lg aspect-square w-[96px] sm:w-[144px] self-start object-cover"
      />
    </router-link>
    <div class="flex flex-col grow min-w-0">
      <div class="flex flex-row justify-space-between">
        <router-link :to="{name: 'product', params: {productId: product.id}}"
                     class="block font-bold cursor-default truncate">
          <span :title="product.name">{{ product.name }}</span>
        </router-link>
        <span class="block font-bold shrink-0 ml-2">{{ formattedPrice }}</span>
      </div>
      <router-link :to="{name: 'product', params: {productId: product.id}}">
        <p class="text-cinder break-words" :title="product.description">{{ product.description }}</p>
      </router-link>
      <div v-if="mode === 'favorite'" class="mt-7 flex flex-row gap-5">
        <c-button-secondary type="button" v-if="!isProductInCart(product.id)" @click="handleMoveItemToCart()"
                            :text="$t('moveToCart')" data-cy="move-item-to-cart-button" />
        <c-button-secondary type="button" data-cy="remove-item-from-favorites-button" @click="handleRemoveItemFromFavorites()" :text="$t('remove')" />
      </div>
      <div v-else class="mt-7 flex flex-row gap-5 flex-wrap">
         <c-menu
          is-radio
          :items="quantityValues"
        >
          <template #activator>
            <c-button-primary
              type="button"
              :text="amount.toString()"
              icon-end="fa-solid fa-chevron-down"
            ></c-button-primary>
          </template>
        </c-menu>
        <c-button-secondary v-if="!isProductInFavorites(product.id)" type="button" :text="$t('moveToFavorites')"
                            @click="handleMoveToFavorites()" />
        <c-button-secondary type="button" data-cy="remove-item-from-cart-button" @click="handleRemoveItemFromCart()"
                            :text="$t('remove')" />
      </div>
    </div>
  </div>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary";
import CMenu from "@/components/common/CMenu";
import CButtonPrimary from "@/components/common/CButtonPrimary";
import { stringFormatter } from "@/util/stringFormatter";
import cartProductMixin from "@/components/cart_view/cartProductMixin";
import favoritesProductMixin from "@/components/favorites_view/favoritesProductMixin";

export default {
  name: "ProductsListItem",
  components: {
    CButtonSecondary,
    CMenu,
    CButtonPrimary
  },
  mixins: [cartProductMixin, favoritesProductMixin],
  props: {
    mode: {
      type: String,
      default: "favorite"
    },
    product: {
      type: Object,
      required: true
    },
    amount: {
      type: Number
    }
  },
  computed: {
    formattedPrice() {
      if (this.mode === "cart") {
        return stringFormatter.getFormattedPrice(this.product.price * this.amount);
      } else {
        return stringFormatter.getFormattedPrice(this.product.price);
      }
    },
    quantityValues() {
      if (this.mode === "cart") {
        return Array.from({ length: 20 }, (_, i) => i + 1).map((value) => ({
          name: value.toString(),
          selected: value.toString() === this.amount.toString(),
          function: () => this.handleQuantityChange(value)
        }));
      }
      return [];
    }
  },
  methods: {
    handleRemoveItemFromCart() {
      this.$store.dispatch("cartModule/removeProductFromCart", { productId: this.product.id, isInstantLoading: true });
    },
    handleQuantityChange(value) {
      this.$store.dispatch("cartModule/updateProductAmount", { productId: this.product.id, amount: value });
    },
    handleMoveToFavorites() {
      this.$store.dispatch("favoritesModule/addProductToFavorites", this.product.id);
      this.$store.dispatch("cartModule/removeProductFromCart", { productId: this.product.id, isInstantLoading: true });
    },
    handleMoveItemToCart() {
      this.$store.dispatch("cartModule/addProductToCart", this.product.id);
      this.$store.dispatch("favoritesModule/removeProductFromFavorites", {
        productId: this.product.id,
        isInstantLoading: true
      });
    },
    handleRemoveItemFromFavorites() {
      this.$store.dispatch("favoritesModule/removeProductFromFavorites", {
        productId: this.product.id,
        isInstantLoading: true
      });
    }
  }
};
</script>

<style scoped>
p {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  -webkit-line-clamp: 2; /* number of lines to show */
  line-clamp: 2;
  -webkit-box-orient: vertical;
}

a {
  @apply cursor-default;
}
</style>
