// bachelor-front-vue-version-main/src/components/common/CButtonPrimary.vue
<template>
  <button
    v-on="$listeners"
    v-bind="$attrs"
    :disabled="isDisabled"
    :class="{
      'h-8 px-2': size === 'small',
      'h-14 px-5': size === 'medium',
      'text-mid-gray hover-is-disabled border-spun-pearl hover:border-spun-pearl': isDisabled,
    }"
    class="flex flex-none items-center tracking-[unset] hover:text-dark-blue hover:border-dark-blue border border-solid border-mid-gray rounded-lg"
  >
    <font-awesome-icon
      v-if="iconStart"
      :class="{ 'mr-2': size === 'small', 'mr-3': size === 'medium' }"
      :icon="iconStart"
      :size="getIconSize()"
    />
    <span
      :class="{ 'c-text-12': size === 'small', 'c-text-14': size === 'medium' }"
    >{{ text }}</span
    >
    <font-awesome-icon
      v-if="iconEnd"
      :class="{ 'ml-2': size === 'small', 'ml-3': size === 'medium' }"
      :icon="iconEnd"
      :size="getIconSize()"
    />
  </button>
</template>

<script>
export default {
  name: "CButtonPrimary",
  props: {
    text: {
      type: String,
      required: true
    },
    iconStart: {
      type: String
    },
    iconEnd: {
      type: String
    },
    size: {
      type: String,
      default: "small"
    },
    isDisabled: {
      type: Boolean,
      default: false
    }
  },
  methods: {
    getIconSize() {
      if (this.size === "small") return "2xs";
      if (this.size === "medium") return "xs";
    }
  }
};
</script>

<style>
.hover-is-disabled:hover {
  color: #69696C !important;
}
</style>

// bachelor-front-react-version-main/src/components/common/CButtonPrimary.tsx
import classNames from "classnames";
import "../../assets/styles/CButtonPrimary.css";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import React, { ButtonHTMLAttributes } from "react";
import { IconProp } from "@fortawesome/fontawesome-svg-core";

interface Props extends ButtonHTMLAttributes<HTMLButtonElement> {
  text: string;
  iconStart?: IconProp;
  iconEnd?: IconProp;
  size?: "small" | "medium";
  isDisabled?: boolean;
  className?: string;
}

function CButtonPrimary(props: Props) {
  const { text, iconStart, iconEnd, size = "small", isDisabled, className, ...buttonProps } = props;

  function getIconSize() {
    if (size === "small") return "2xs";
    if (size === "medium") return "xs";
  }

  return (
    <button
      {...buttonProps}
      className={classNames({
        "h-8 px-2": size === "small",
        "h-14 px-5": size === "medium",
        "text-mid-gray hover-is-disabled border-spun-pearl hover:border-spun-pearl": isDisabled,
        [className || ""]: true,
        "flex flex-none items-center tracking-[unset] hover:text-dark-blue hover:border-dark-blue border border-solid border-mid-gray rounded-lg":
          true,
      })}
      disabled={isDisabled}>
      {iconStart && (
        <FontAwesomeIcon
          icon={iconStart}
          className={classNames({ "mr-2": size === "small", "mr-3": size === "medium" })}
          size={getIconSize()}
        />
      )}
      <span
        className={classNames({
          "c-text-12": size === "small",
          "c-text-14": size === "medium",
        })}>
        {text}
      </span>
      {iconEnd && (
        <FontAwesomeIcon
          icon={iconEnd}
          className={classNames({ "ml-2": size === "small", "ml-3": size === "medium" })}
          size={getIconSize()}
        />
      )}
    </button>
  );
}

export default CButtonPrimary;
