// bachelor-front-vue-version-main/src/components/common/CInfo.vue
<template>
  <div>
    <div :class="classStyling">
      <font-awesome-icon
        icon="fa-solid fa-info"
        class="text-mid-gray mr-3"
        size="sm"
      ></font-awesome-icon>
      <p>
        {{ text }}
      </p>
    </div>
  </div>
</template>

<script>
export default {
  name: "CInfo",
  props: {
    text: {
      type: String,
      required: true
    },
    type: {
      type: String,
      default: "info"
    },
    size: {
      type: String,
      default: "md"
    }
  },
  computed: {
    classStyling() {
      let baseClasses = "border border-spun-pearl border-solid flex inline-flex";
      if (this.type === "error") {
        baseClasses += " bg-background-error";
      }
      if (this.type === "warning") {
        baseClasses += " bg-background-warning";
      }
      if (this.type === "success") {
        baseClasses += " bg-background-success";
      }
      if (this.size === "sm") {
        baseClasses += " pa-1";
      }
      if (this.size === "md") {
        baseClasses += " pa-4";
      }
      return baseClasses;
    }
  }
};
</script>

<style scoped></style>

// bachelor-front-react-version-main/src/components/common/CInfo.tsx
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

interface Props {
  text?: string;
  type?: "info" | "success" | "warning" | "error";
  size?: "sm" | "md";
  className?: string;
}

function CInfo(props: Props) {
  const { text, type = "info", size = "md", className = "" } = props;

  function getClassStyling() {
    let baseClasses = className + " border border-spun-pearl border-solid flex inline-flex";
    if (type === "error") {
      baseClasses += " bg-background-error";
    }
    if (type === "warning") {
      baseClasses += " bg-background-warning";
    }
    if (type === "success") {
      baseClasses += " bg-background-success";
    }
    if (size === "sm") {
      baseClasses += " p-1";
    }
    if (size === "md") {
      baseClasses += " p-4";
    }
    return baseClasses;
  }

  return (
    <div className={getClassStyling()}>
      <FontAwesomeIcon icon={["fas", "info"]} className="text-mid-gray mr-3" size="sm"></FontAwesomeIcon>
      <p className="text">{text}</p>
    </div>
  );
}

export default CInfo;
