// bachelor-front-vue-version-main/src/components/common/CRating.vue
<template>
  <div class="flex flex-col" v-on="$listeners">
    <div class="flex items-center">
      <v-rating half-increments :value="value">
        <template v-slot:item="props">
        <span v-if="props.isHalfFilled" class="mr-1"
              data-test="half-star">
          <font-awesome-icon
            size="xs"
            icon="fa-solid fa-star-half"
            class="relative z-[1]"
          />
          <span class="c-invisible-wrapper inline-block">
            <font-awesome-icon
              size="xs"
              class="text-spun-pearl absolute right-0 bottom-0"
              icon="fa-solid fa-star"
            />
          </span>
        </span>
          <font-awesome-icon
            data-test="filled-star"
            class="mr-1"
            v-else-if="props.isFilled"
            size="xs"
            icon="fa-solid fa-star"
          />
          <font-awesome-icon
            data-test="empty-star"
            size="xs"
            v-else
            class="text-spun-pearl mr-1"
            icon="fa-solid fa-star"
          />
        </template>
      </v-rating>
      <div>
      <span v-if="isNumericRatingShown" class="c-text-12 ml-1" style="vertical-align: text-bottom" data-test="value">
        ({{ formattedValue }})
      </span>
      </div>
    </div>
    <div v-if="isTotalRatingShown" class="c-text-12 text-mid-gray leading-1.5">
      {{ totalRatings }} {{ $t("ratingsInTotal").toLowerCase() }}
    </div>
  </div>
</template>

<script>
import { stringFormatter } from "@/util/stringFormatter";

export default {
  name: "CRating",
  props: {
    value: {
      type: Number,
      required: true
    },
    totalRatings: {
      type: Number
    },
    isTotalRatingShown: {
      type: Boolean
    },
    isNumericRatingShown: {
      type: Boolean,
      default: true
    }
  },
  computed: {
    formattedValue() {
      return stringFormatter.replaceDotsWithCommas(this.value);
    }
  }
};
</script>

<style scoped></style>

// bachelor-front-react-version-main/src/components/common/CRating.tsx
import { stringFormatterHelper } from "../../utils/stringFormatterHelper";
import { HTMLAttributes } from "react";
import Rating from "@mui/material/Rating";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useTranslation } from "react-i18next";

interface Props extends HTMLAttributes<HTMLDivElement> {
  value: number;
  totalRatings: number;
  isTotalRatingShown?: boolean;
  isNumericRatingShown?: boolean;
}

function CRating(props: Props) {
  const { value, totalRatings, isTotalRatingShown, isNumericRatingShown = true, ...divAttributes } = props;
  const { t } = useTranslation();

  function getFormattedValue() {
    return stringFormatterHelper.replaceDotsWithCommas(value.toString());
  }

  return (
    <div className="flex flex-col" {...divAttributes}>
      <div className="flex items-center">
        <Rating
          readOnly
          precision={0.5}
          value={value}
          icon={<FontAwesomeIcon icon={["fas", "star"]} className="text-cinder mr-1" size="2xs" />}
          emptyIcon={<FontAwesomeIcon icon={["fas", "star"]} className="text-spun-pearl mr-1" size="2xs" />}
        />
        <div>
          {isNumericRatingShown && (
            <span className="c-text-12 ml-1" style={{ verticalAlign: "text-bottom" }}>
              {getFormattedValue()}
            </span>
          )}
        </div>
      </div>
      {isTotalRatingShown && (
        <div className="c-text-12 text-mid-gray leading-1.5">
          {totalRatings} {t("ratingsInTotal").toLowerCase()}
        </div>
      )}
    </div>
  );
}

export default CRating;
