// bachelor-front-vue-version-main/src/components/business_management_tool_view/EditProduct.vue
<template>
  <form class="flex flex-col">
    <c-input
      data-cy="product-name-input"
      ref="cInputName"
      v-model="name"
      size="medium"
      :label-text="$t('name') + ' *'"
      :validator-functions="[validateRequired]"
    ></c-input>
    <c-textarea
      ref="cTextareaDescription"
      v-model="description"
      :label-text="$t('description') + ' *'"
      :validator-functions="[validateRequired]"
      class="mt-8"
    ></c-textarea>
    <span class="block c-text-14 mt-8 mb-2">
      {{ $t("category") + " *" }}
    </span>
    <div class="inline-block">
      <c-menu is-radio :items="categories">
        <template #activator>
          <c-button-primary
            type="button"
            :text="selectedCategory"
            icon-end="fa-solid fa-chevron-down"
          ></c-button-primary>
        </template>
      </c-menu>
    </div>
    <p style="max-width: calc(96px * 4)" class="mt-2">
      {{ $t("ifYouCannotTheCategoryThatFitsTheProductYouCan") }}
    </p>
    <c-info
      class="mt-10"
      :text="$t('theFilesBelowHaveToBeInPngCommaJpgOrJpegFormat')"
    ></c-info>
    <c-file-input
      :non-native-file-name="mainImageKey ? $t('someImageUploaded') : ''"
      accept="image/png, image/jpeg, image/jpg"
      class="mt-8"
      :label-text="$t('mainImage') + ' *'"
      ref="cFileInputMainImage"
      @fileSelected="handleMainImageSelected"
      :description-text="$t('mainImageDescription')"
    ></c-file-input>
    <c-file-input
      :non-native-file-name="image1Key ? $t('someImageUploaded') : ''"
      accept="image/png, image/jpeg, image/jpg"
      class="mt-8"
      :label-text="$t('image') + ' 1'"
      ref="cFileInputImage1"
      @fileSelected="file => handleSecondaryImageSelected(file, 1)"
      :description-text="$t('firstSecondaryImageDescription')"
    ></c-file-input>
    <c-file-input
      :non-native-file-name="image2Key ? $t('someImageUploaded') : ''"
      accept="image/png, image/jpeg, image/jpg"
      class="mt-8"
      :label-text="$t('image') + ' 2'"
      ref="cFileInputImage2"
      @fileSelected="file => handleSecondaryImageSelected(file, 2)"
    ></c-file-input>
    <c-file-input
      :non-native-file-name="image3Key ? $t('someImageUploaded') : ''"
      accept="image/png, image/jpeg, image/jpg"
      class="mt-8"
      :label-text="$t('image') + ' 3'"
      ref="cFileInputImage3"
      @fileSelected="file => handleSecondaryImageSelected(file, 3)"
    ></c-file-input>
    <c-file-input
      :non-native-file-name="image4Key ? $t('someImageUploaded') : ''"
      accept="image/png, image/jpeg, image/jpg"
      class="mt-8"
      :label-text="$t('image') + ' 4'"
      ref="cFileInputImage4"
      @fileSelected="file => handleSecondaryImageSelected(file, 4)"
    ></c-file-input>
    <c-file-input
      :non-native-file-name="image5Key ? $t('someImageUploaded') : ''"
      accept="image/png, image/jpeg, image/jpg"
      class="mt-8"
      :label-text="$t('image') + ' 5'"
      ref="cFileInputImage5"
      @fileSelected="file => handleSecondaryImageSelected(file, 5)"
    ></c-file-input>
    <c-input
      ref="cInputPrice"
      v-model="price"
      size="medium"
      class="mt-8"
      :label-text="$t('pricePerUnit') + ' (MDL) *'"
      :validator-functions="[validateRequired, validateIsFloat, validateIsPositive]"
    ></c-input>
    <c-input
      ref="cInputAmountInStock"
      v-model="amountInStock"
      size="medium"
      class="mt-8"
      :label-text="$t('itemsInStock') + ' *'"
      :validator-functions="[validateRequired, validateIsInteger, validateIsPositive]"
    ></c-input>
    <div class="mt-8 flex items-center justify-end gap-x-6" data-test="footer">
      <c-button-secondary type="button" @click="$emit('close')" :text="$t('cancel')"></c-button-secondary>
      <c-button-primary data-cy="save-product-button" type="button" @click="handleSaveProduct()" :text="$t('confirm')"></c-button-primary>
    </div>
  </form>
</template>

<script lang="ts">
import CInput from "@/components/common/CInput";
import validatorMixin from "@/util/validatorMixin";
import CTextarea from "@/components/common/CTextarea";
import CMenu from "@/components/common/CMenu";
import CButtonPrimary from "@/components/common/CButtonPrimary";
import CFileInput from "@/components/common/CFileInput";
import CInfo from "@/components/common/CInfo";
import CButtonSecondary from "@/components/common/CButtonSecondary";
import Vue from "vue";
import { PatchProductRequest, ProductRequest } from "@/generated-sources/openapi";
import { stringFormatter } from "@/util/stringFormatter";

export default Vue.extend({
  name: "EditProduct",
  mixins: [validatorMixin],
  components: {
    CInput,
    CTextarea,
    CMenu,
    CButtonPrimary,
    CFileInput,
    CInfo,
    CButtonSecondary
  },
  props: {
    product: {
      type: Object
    }
  },
  computed: {
    categories() {
      return this.$store.state.productModule.categories.map(category => {
        return {
          name: this.$t(category.category),
          selected: category.id === this.categoryId,
          function: () => {
            this.categoryId = category.id;
          }
        };
      });
    },
    selectedCategory() {
      let categoryName = this.$store.state.productModule.categories
        .find(category => category.id === this.categoryId)?.category;
      return categoryName ? this.$t(categoryName) : "...";
    }
  },
  data() {
    return {
      name: null,
      description: null,
      categoryId: null,
      price: null,
      amountInStock: null,

      mainImageKey: null,
      mainImageUrl: null,
      image1Key: null,
      image1Url: null,
      image2Key: null,
      image2Url: null,
      image3Key: null,
      image3Url: null,
      image4Key: null,
      image4Url: null,
      image5Key: null,
      image5Url: null
    };
  },
  created() {
    if (!this.$store.state.productModule.categories.length) {
      this.$store.dispatch("productModule/fetchCategories", true)
        .then(() => {
          if (!this.product)
            this.categoryId = this.$store.state.productModule.categories[0].id;
        })
        .catch(() => {
          this.$emit("close");
        });
    } else {
      if (!this.product)
        this.categoryId = this.$store.state.productModule.categories[0].id;
    }

    if (this.product) {
      this.name = this.product.name;
      this.price = this.product.price + '';
      this.categoryId = this.product.categoryId;
      this.description = this.product.description;
      this.amountInStock = this.product.stockAmount + '';
      this.mainImageKey = this.product.mainImage.imageKey;
      this.mainImageUrl = this.product.mainImage.imageUrl;

      this.product.additionalImages.forEach((image, index) => {
        this[`image${index + 1}Key`] = image.imageKey;
        this[`image${index + 1}Url`] = image.imageUrl;
      });
    }
  },
  methods: {
    handleMainImageSelected(file) {
      this.$store.dispatch("businessManagementToolModule/uploadProductImage", file)
        .then(response => {
          this.mainImageKey = response.data.imageKey;
          this.mainImageUrl = response.data.imageUrl;
        })
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", { message: this.$t("somethingWentWrong"), type: "error" });
          this.$refs.cFileInputMainImage.reset();
          this.$refs.cFileInputMainImage.validateInput();
        });
    },
    handleSecondaryImageSelected(file, imageNumber) {
      this.$store.dispatch("businessManagementToolModule/uploadProductImage", file)
        .then(response => {
          this[`image${imageNumber}Key`] = response.data.imageKey;
          this[`image${imageNumber}Url`] = response.data.imageUrl;
        })
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", { message: this.$t("somethingWentWrong"), type: "error" });
          this.$refs[`cFileInputImage${imageNumber}`].reset();
        });
    },
    validateMainImage() {
      if (this.mainImageKey && this.mainImageUrl) {
        return true;
      } else {
        this.$refs.cFileInputMainImage.reset();
        return this.$refs.cFileInputMainImage.validateInput();
      }
    },
    handleSaveProduct() {
      let isNameValid = this.$refs.cInputName.validateInput();
      let isDescriptionValid = this.$refs.cTextareaDescription.validateInput();
      let isPriceValid = this.$refs.cInputPrice.validateInput();
      let isAmountInStockValid = this.$refs.cInputAmountInStock.validateInput();
      let isMainImageValid = this.validateMainImage();

      if (isNameValid && isDescriptionValid && isPriceValid && isAmountInStockValid && isMainImageValid) {
        let additionalImages = [];

        if (this.image1Key && this.image1Url) {
          additionalImages.push({ imageKey: this.image1Key, imageUrl: this.image1Url });
        }
        if (this.image2Key && this.image2Url) {
          additionalImages.push({ imageKey: this.image2Key, imageUrl: this.image2Url });
        }
        if (this.image3Key && this.image3Url) {
          additionalImages.push({ imageKey: this.image3Key, imageUrl: this.image3Url });
        }
        if (this.image4Key && this.image4Url) {
          additionalImages.push({ imageKey: this.image4Key, imageUrl: this.image4Url });
        }
        if (this.image5Key && this.image5Url) {
          additionalImages.push({ imageKey: this.image5Key, imageUrl: this.image5Url });
        }

        if (this.product) {
          let patchProductRequest: PatchProductRequest = {
            id: this.product.id,
            name: this.name,
            price: stringFormatter.replaceCommasWithDots(this.price),
            categoryId: this.categoryId,
            description: this.description,
            stockAmount: this.amountInStock,
            mainImage: {
              imageKey: this.mainImageKey,
              imageUrl: this.mainImageUrl
            },
            additionalImages: additionalImages
          };

          this.$store.dispatch("businessManagementToolModule/updateProduct", patchProductRequest)
            .then(() => {
                this.$emit("close");
                this.$store.dispatch("businessManagementToolModule/fetchProducts", 1);
              }
            )
            .catch(() => this.$store.dispatch("eventModule/showSnackbar", {
              message: this.$t("somethingWentWrong"),
              type: "error"
            }));

        } else {
          let productRequest: ProductRequest = {
            name: this.name,
            price: stringFormatter.replaceCommasWithDots(this.price),
            categoryId: this.categoryId,
            description: this.description,
            stockAmount: this.amountInStock,
            mainImage: {
              imageKey: this.mainImageKey,
              imageUrl: this.mainImageUrl
            },
            additionalImages: additionalImages
          };

          this.$store.dispatch("businessManagementToolModule/createProduct", productRequest)
            .then(() => {
                this.$emit("close");
                this.$store.dispatch("businessManagementToolModule/fetchProducts", 1);
              }
            )
            .catch(() => this.$store.dispatch("eventModule/showSnackbar", {
              message: this.$t("somethingWentWrong"),
              type: "error"
            }));
        }
      }
    }
  }
});
</script>

<style scoped>

</style>

// bachelor-front-react-version-main/src/components/business-management-tool/EditProduct.tsx
import { PatchProductRequest, Product, ProductRequest } from "../../generated-sources/openapi";
import { useEffect, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { useTranslation } from "react-i18next";
import CInput from "../common/CInput";
import { validatorHelper } from "../../utils/validatorHelper";
import CTextarea from "../common/CTextarea";
import { RootState } from "../../store";
import { fetchCategories } from "../../store/productSlice";
import {
  createProduct,
  fetchProducts,
  updateProduct,
  uploadProductImage,
} from "../../store/businessManagementToolSlice";
import { showSnackbar } from "../../store/eventSlice";
import { stringFormatterHelper } from "../../utils/stringFormatterHelper";
import CMenu from "../common/CMenu";
import CButtonPrimary from "../common/CButtonPrimary";
import CInfo from "../common/CInfo";
import CFileInput from "../common/CFileInput";
import CButtonSecondary from "../common/CButtonSecondary";

interface Props {
  onClose: () => void;
  className?: string;
  product?: Product;
}

function EditProduct(props: Props) {
  const dispatch = useDispatch();
  const { t } = useTranslation();

  const { onClose, className = "", product } = props;

  const { categories } = useSelector((state: RootState) => state.product);

  const cInputNameRef = useRef<any>(null);
  const cTextareaDescriptionRef = useRef<any>(null);
  const cFileInputMainImageRef = useRef<any>(null);
  const cFileInputImage1Ref = useRef<any>(null);
  const cFileInputImage2Ref = useRef<any>(null);
  const cFileInputImage3Ref = useRef<any>(null);
  const cFileInputImage4Ref = useRef<any>(null);
  const cFileInputImage5Ref = useRef<any>(null);
  const cInputPriceRef = useRef<any>(null);
  const cInputAmountInStockRef = useRef<any>(null);

  const [name, setName] = useState<any>("");
  const [description, setDescription] = useState<any>("");
  const [categoryId, setCategoryId] = useState<any>(null);
  const [price, setPrice] = useState<any>(null);
  const [amountInStock, setAmountInStock] = useState("");
  const [mainImageKey, setMainImageKey] = useState<any>("");
  const [mainImageUrl, setMainImageUrl] = useState<any>("");
  const [image1Key, setImage1Key] = useState<any>("");
  const [image1Url, setImage1Url] = useState<any>("");
  const [image2Key, setImage2Key] = useState<any>("");
  const [image2Url, setImage2Url] = useState<any>("");
  const [image3Key, setImage3Key] = useState<any>("");
  const [image3Url, setImage3Url] = useState<any>("");
  const [image4Key, setImage4Key] = useState<any>("");
  const [image4Url, setImage4Url] = useState<any>("");
  const [image5Key, setImage5Key] = useState<any>("");
  const [image5Url, setImage5Url] = useState<any>("");

  const categorySelectorItems = categories.map((category) => {
    return {
      text: t(category.category || "") || "",
      label: category.id === categoryId,
      function: () => setCategoryId(category.id),
    };
  });

  const selectedCategoryName = categories.find((category) => category.id === categoryId)?.category || "...";

  useEffect(() => {
    if (!categories.length) {
      // @ts-ignore
      dispatch(fetchCategories(true))
        .then(() => {
          if (!product) setCategoryId(categories[0].id);
        })
        .catch(() => onClose());
    } else {
      if (!product) setCategoryId(categories[0].id);
    }

    if (product) {
      setName(product.name);
      setPrice(product.price + "");
      setCategoryId(product.categoryId);
      setDescription(product.description);
      setAmountInStock(product.stockAmount + "");
      setMainImageKey(product.mainImage?.imageKey);
      setMainImageUrl(product.mainImage?.imageUrl);

      setImage1Key(product.additionalImages?.at(0)?.imageKey);
      setImage1Url(product.additionalImages?.at(0)?.imageUrl);
      setImage2Key(product.additionalImages?.at(1)?.imageKey);
      setImage2Url(product.additionalImages?.at(1)?.imageUrl);
      setImage3Key(product.additionalImages?.at(2)?.imageKey);
      setImage3Url(product.additionalImages?.at(2)?.imageUrl);
      setImage4Key(product.additionalImages?.at(3)?.imageKey);
      setImage4Url(product.additionalImages?.at(3)?.imageUrl);
      setImage5Key(product.additionalImages?.at(4)?.imageKey);
      setImage5Url(product.additionalImages?.at(4)?.imageUrl);
    }
  }, []);

  function handleMainImageSelected(file: File) {
    // @ts-ignore
    dispatch(uploadProductImage(file))
      .then((response: any) => {
        setMainImageKey(response.data.imageKey);
        setMainImageUrl(response.data.imageUrl);
      })
      .catch(() => {
        dispatch(
          showSnackbar({
            message: t("somethingWentWrong"),
            type: "error",
          })
        );
        cFileInputMainImageRef.current.reset();
        cFileInputMainImageRef.current.validateInput();
      });
  }

  function handleSecondaryImageSelected(file: File, imageNumber: number) {
    // @ts-ignore
    dispatch(uploadProductImage(file))
      .then((response: any) => {
        if (imageNumber === 1) {
          setImage1Key(response.data.imageKey);
          setImage1Url(response.data.imageUrl);
        } else if (imageNumber === 2) {
          setImage2Key(response.data.imageKey);
          setImage2Url(response.data.imageUrl);
        } else if (imageNumber === 3) {
          setImage3Key(response.data.imageKey);
          setImage3Url(response.data.imageUrl);
        } else if (imageNumber === 4) {
          setImage4Key(response.data.imageKey);
          setImage4Url(response.data.imageUrl);
        } else if (imageNumber === 5) {
          setImage5Key(response.data.imageKey);
          setImage5Url(response.data.imageUrl);
        }
      })
      .catch(() => {
        dispatch(
          showSnackbar({
            message: t("somethingWentWrong"),
            type: "error",
          })
        );
        if (imageNumber === 1) {
          cFileInputImage1Ref.current.reset();
        } else if (imageNumber === 2) {
          cFileInputImage2Ref.current.reset();
        } else if (imageNumber === 3) {
          cFileInputImage3Ref.current.reset();
        } else if (imageNumber === 4) {
          cFileInputImage4Ref.current.reset();
        } else if (imageNumber === 5) {
          cFileInputImage5Ref.current.reset();
        }
      });
  }

  function validateMainImage(): boolean {
    if (mainImageKey && mainImageUrl) {
      return true;
    } else {
      cFileInputMainImageRef.current.reset();
      return cFileInputMainImageRef.current.validateInput();
    }
  }

  function handleSaveProduct(e?: any) {
    e?.preventDefault();

    let isNameValid = cInputNameRef.current.validateInput();
    let isDescriptionValid = cTextareaDescriptionRef.current.validateInput();
    let isPriceValid = cInputPriceRef.current.validateInput();
    let isAmountInStockValid = cInputAmountInStockRef.current.validateInput();
    let isMainImageValid = validateMainImage();

    if (isNameValid && isDescriptionValid && isPriceValid && isAmountInStockValid && isMainImageValid) {
      let additionalImages = [];

      if (image1Key && image1Url) {
        additionalImages.push({ imageKey: image1Key, imageUrl: image1Url });
      }
      if (image2Key && image2Url) {
        additionalImages.push({ imageKey: image2Key, imageUrl: image2Url });
      }
      if (image3Key && image3Url) {
        additionalImages.push({ imageKey: image3Key, imageUrl: image3Url });
      }
      if (image4Key && image4Url) {
        additionalImages.push({ imageKey: image4Key, imageUrl: image4Url });
      }
      if (image5Key && image5Url) {
        additionalImages.push({ imageKey: image5Key, imageUrl: image5Url });
      }

      if (product) {
        let patchProductRequest: PatchProductRequest = {
          id: product.id + "",
          name: name,
          price: parseFloat(stringFormatterHelper.replaceCommasWithDots(price)),
          categoryId: categoryId,
          description: description,
          stockAmount: parseInt(amountInStock),
          mainImage: {
            imageKey: mainImageKey,
            imageUrl: mainImageUrl,
          },
          additionalImages: additionalImages,
        };

        // @ts-ignore
        dispatch(updateProduct(patchProductRequest))
          .then(() => {
            onClose();
            // @ts-ignore
            dispatch(fetchProducts(1));
          })
          .catch(() =>
            dispatch(
              showSnackbar({
                message: t("somethingWentWrong"),
                type: "error",
              })
            )
          );
      } else {
        let productRequest: ProductRequest = {
          name: name,
          price: parseFloat(stringFormatterHelper.replaceCommasWithDots(price)),
          categoryId: categoryId,
          description: description,
          stockAmount: parseInt(amountInStock),
          mainImage: {
            imageKey: mainImageKey,
            imageUrl: mainImageUrl,
          },
          additionalImages: additionalImages,
        };

        // @ts-ignore
        dispatch(createProduct(productRequest))
          .then(() => {
            onClose();
            // @ts-ignore
            dispatch(fetchProducts(1));
          })
          .catch(() =>
            dispatch(
              showSnackbar({
                message: t("somethingWentWrong"),
                type: "error",
              })
            )
          );
      }
    }
  }

  return (
    <form className={className + " flex flex-col"} onSubmit={handleSaveProduct}>
      <CInput
        ref={cInputNameRef}
        value={name || ""}
        onUpdate={setName}
        inputSize={"medium"}
        labelText={t("name") + " *"}
        validatorFunctions={[validatorHelper.validateRequired]}></CInput>
      <CTextarea
        ref={cTextareaDescriptionRef}
        value={description || ""}
        onUpdate={setDescription}
        labelText={t("description") + " *"}
        validatorFunctions={[validatorHelper.validateRequired]}
        className={"mt-8"}></CTextarea>
      <span className="block c-text-14 mt-8 mb-2">{t("category") + " *"}</span>
      <div className="inline-block">
        <CMenu isRadio={true} items={categorySelectorItems}>
          <CButtonPrimary iconEnd={["fas", "chevron-down"]} type="button" text={selectedCategoryName}></CButtonPrimary>
        </CMenu>
      </div>
      <p className={"max-w-sm mt-2"}>{t("ifYouCannotTheCategoryThatFitsTheProductYouCan")}</p>
      <CInfo className={"mt-10"} text={t("theFilesBelowHaveToBeInPngCommaJpgOrJpegFormat") || ""}></CInfo>
      <CFileInput
        nonNativeFileName={mainImageKey ? t("someImageUploaded") || "" : ""}
        accept="image/png, image/jpeg, image/jpg"
        className={"mt-8"}
        labelText={t("mainImage") + " *"}
        ref={cFileInputMainImageRef}
        onFileSelected={handleMainImageSelected}
        descriptionText={t("mainImageDescription") || ""}></CFileInput>
      <CFileInput
        nonNativeFileName={image1Key ? t("someImageUploaded") || "" : ""}
        accept="image/png, image/jpeg, image/jpg"
        className={"mt-8"}
        labelText={t("image") + " 1"}
        ref={cFileInputImage1Ref}
        onFileSelected={(file) => handleSecondaryImageSelected(file, 1)}
        descriptionText={t("firstSecondaryImageDescription") || ""}></CFileInput>
      <CFileInput
        nonNativeFileName={image2Key ? t("someImageUploaded") || "" : ""}
        accept="image/png, image/jpeg, image/jpg"
        className={"mt-8"}
        labelText={t("image") + " 2"}
        ref={cFileInputImage2Ref}
        onFileSelected={(file) => handleSecondaryImageSelected(file, 2)}></CFileInput>
      <CFileInput
        nonNativeFileName={image3Key ? t("someImageUploaded") || "" : ""}
        accept="image/png, image/jpeg, image/jpg"
        className={"mt-8"}
        labelText={t("image") + " 3"}
        ref={cFileInputImage3Ref}
        onFileSelected={(file) => handleSecondaryImageSelected(file, 3)}></CFileInput>
      <CFileInput
        nonNativeFileName={image4Key ? t("someImageUploaded") || "" : ""}
        accept="image/png, image/jpeg, image/jpg"
        className={"mt-8"}
        labelText={t("image") + " 4"}
        ref={cFileInputImage4Ref}
        onFileSelected={(file) => handleSecondaryImageSelected(file, 4)}></CFileInput>
      <CFileInput
        nonNativeFileName={image5Key ? t("someImageUploaded") || "" : ""}
        accept="image/png, image/jpeg, image/jpg"
        className={"mt-8"}
        labelText={t("image") + " 5"}
        ref={cFileInputImage5Ref}
        onFileSelected={(file) => handleSecondaryImageSelected(file, 5)}></CFileInput>
      <CInput
        className={"mt-8"}
        ref={cInputPriceRef}
        value={price || ""}
        onUpdate={setPrice}
        inputSize={"medium"}
        labelText={t("pricePerUnit") + " (MDL) *"}
        validatorFunctions={[
          validatorHelper.validateRequired,
          validatorHelper.validateIsFloat,
          validatorHelper.validateIsPositive,
        ]}></CInput>
      <CInput
        className={"mt-8"}
        ref={cInputAmountInStockRef}
        value={amountInStock || ""}
        onUpdate={setAmountInStock}
        inputSize={"medium"}
        labelText={t("itemsInStock") + " *"}
        validatorFunctions={[
          validatorHelper.validateRequired,
          validatorHelper.validateIsInteger,
          validatorHelper.validateIsPositive,
        ]}></CInput>
      <div className="mt-8 flex items-center justify-end gap-x-6">
        <CButtonSecondary type="button" onClick={onClose} text={t("cancel")}></CButtonSecondary>
        <CButtonPrimary type="button" onClick={handleSaveProduct} text={t("confirm")}></CButtonPrimary>
      </div>
    </form>
  );
}

export default EditProduct;
