// bachelor-front-vue-version-main/src/components/business_management_tool_view/ProductListItem.vue
<template>
  <div class="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
    <span class="c-text-14 truncate">{{ product.name }}</span>
    <div class="flex items-center gap-x-3 flex-wrap">
      <router-link target="_blank" :to="{name: 'product', params: {productId: product.id}}">
        <c-button-secondary :text="$t('view')"></c-button-secondary>
      </router-link>
      <c-button-secondary data-cy="edit-product-button" @click="isProductEditDialogShown = true" :text="$t('edit')"></c-button-secondary>
      <c-button-secondary data-cy="delete-product-button" @click="isProductDeleteDialogShown = true" :text="$t('delete')"></c-button-secondary>
    </div>
    <c-dialog v-model="isProductEditDialogShown">
      <template #title>
        <h3>{{ $t("editProduct") }}</h3>
      </template>
      <template #body>
        <edit-product :product="product" @close="isProductEditDialogShown = false" class="mt-8"></edit-product>
      </template>
      <template #footer>
        <div></div>
      </template>
    </c-dialog>
    <c-dialog :title-text="$t('deleteProduct')" :subtitle-text="$t('doYouReallyWantToDelete', {name: product.name})"
              v-model="isProductDeleteDialogShown" @confirm="handleConfirmDeleteProduct()"></c-dialog>
  </div>
</template>

<script>
import CButtonSecondary from "@/components/common/CButtonSecondary";
import CDialog from "@/components/common/CDialog";
import EditProduct from "@/components/business_management_tool_view/EditProduct";

export default {
  name: "ProductListItem",
  components: {
    CButtonSecondary,
    CDialog,
    EditProduct
  },
  props: {
    product: {
      type: Object,
      required: true
    }
  },
  data() {
    return {
      isProductEditDialogShown: false,
      isProductDeleteDialogShown: false
    };
  },
  methods: {
    handleConfirmDeleteProduct() {
      this.$store.dispatch("businessManagementToolModule/deleteProduct", this.product.id)
        .then(() => {
          this.isProductDeleteDialogShown = false;
          this.$store.dispatch("businessManagementToolModule/fetchProducts", 1);
        })
        .catch(() => {
          this.$store.dispatch("eventModule/showSnackbar", {
            message: this.$t("somethingWentWrong"),
            type: "error"
          });
        });
    },
  }
};
</script>

<style scoped>

</style>

// bachelor-front-react-version-main/src/components/business-management-tool/ProductListItem.tsx
import { Product } from "../../generated-sources/openapi";
import { useState } from "react";
import { useDispatch } from "react-redux";
import { deleteProduct, fetchProducts } from "../../store/businessManagementToolSlice";
import { showSnackbar } from "../../store/eventSlice";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import CButtonSecondary from "../common/CButtonSecondary";
import CDialog from "../common/CDialog";
import EditProduct from "./EditProduct";

interface Props {
  product: Product;
}

function ProductListItem(props: Props) {
  const dispatch = useDispatch();
  const { t } = useTranslation();

  const { product } = props;

  const [isProductEditDialogShown, setIsProductEditDialogShown] = useState(false);
  const [isProductDeleteDialogShown, setIsProductDeleteDialogShown] = useState(false);

  function handleConfirmDeleteProduct() {
    // @ts-ignore
    dispatch(deleteProduct(product.id))
      .then(() => {
        setIsProductDeleteDialogShown(false);
        // @ts-ignore
        dispatch(fetchProducts(1));
      })
      .catch(() =>
        dispatch(
          showSnackbar({
            message: t("somethingWentWrong"),
            type: "error",
          })
        )
      );
  }

  return (
    <div className="h-14 border border-solid border-mid-gray flex flex-row items-center px-5 justify-between">
      <span className="c-text-14 truncate">{product.name}</span>
      <div className="flex items-center gap-x-3 flex-wrap">
        <Link target="_blank" to={"/product/" + product.id}>
          <CButtonSecondary text={t("view")}></CButtonSecondary>
        </Link>
        <CButtonSecondary text={t("edit")} onClick={() => setIsProductEditDialogShown(true)}></CButtonSecondary>
        <CButtonSecondary text={t("delete")} onClick={() => setIsProductDeleteDialogShown(true)}></CButtonSecondary>
      </div>
      <CDialog
        isShown={isProductEditDialogShown}
        onUpdate={setIsProductEditDialogShown}
        titleSlot={<h3>{t("editProduct")}</h3>}
        footerSlot={<div></div>}>
        <EditProduct
          className={"mt-8"}
          product={product}
          onClose={() => setIsProductEditDialogShown(false)}></EditProduct>
      </CDialog>
      <CDialog
        titleText={t("deleteProduct") || ""}
        subtitleText={t("doYouReallyWantToDelete", { name: product.name }) || ""}
        isShown={isProductDeleteDialogShown}
        onUpdate={setIsProductDeleteDialogShown}
        onConfirm={handleConfirmDeleteProduct}></CDialog>
    </div>
  );
}

export default ProductListItem;
